### ISSUE TITLE
vue-2.0 support

### ISSUE THREAD

**Issue by transtone** [Justineo/vue-echarts#1]
Is there a plan for support vue-2.0?

**Comment by strebl** [comment]
+1

**Comment by strebl** [comment]
👍

**Comment by Justineo** [comment]
2.0 support is planned after Vue.js 2.0 is officially released.

**Comment by SoulFlys** [comment]
vue-cli已经默认2.0了，博主啥时候更新到2.0咩

**Comment by Justineo** [comment]
@SoulFlys 刚把另外两个项目迁移到 2.0，这个再稍微等等。

**Comment by DevilLeven** [comment]
2.0 support https://github.com/DevilLeven/vue2-echarts

**Comment by GloriaCHL** [comment]
请问，你的demo里this.refs.xx都是后面才做操作，可以拿得到。我在父组件的ready里直接拿this.refs.xxx是undefined的，除非写个setTimeout做点延时才可以拿到。
这个有办法解决么？

**Comment by Justineo** [comment]
`vue-echarts@2.0.0` supports Vue `2.0`+ now.
