### ISSUE TITLE
引入echarts-wordcloud就报错了，是不是有什么冲突

### ISSUE THREAD

**Issue by hank2718** [Justineo/vue-echarts#101]
![image](https://user-images.githubusercontent.com/7368299/27677476-66c879e6-5ce4-11e7-8bb9-0a403173c0ab.png)
之前切换路由切换有echarts的页面会报错，后来我直接在报错页面引入echarts-wordcloud直接报错了
![image](https://user-images.githubusercontent.com/7368299/27677519-9cc462a8-5ce4-11e7-9757-61c407b686cb.png)
实际报错的页面我没有用到echarts-wordcloud，图1是我引入的全部echarts依赖了

**Comment by Justineo** [comment]
你要先引入 vue-echarts，再引入插件。
