### ISSUE TITLE
与vue-strap中的modal.vue结合使用，不能渲染出来

### ISSUE THREAD

**Issue by tyhyly** [Justineo/vue-echarts#105]
`<Modal v-model="showChart" @ok="showChart = false">
      <EChart :options="chartOption" :ref="'pie'" :auto-resize="''"></EChart>
 </Modal>`

控制showChart，当点击某按钮时，showChart为true，echarts图标不能显示，调用resize方法也不行，init也不行，从控制台看到实例化dom存在，求解决。

**Comment by tyhyly** [comment]
掉了半天坑，什么resize和init都不好使，最后在

> <EChart v-if="showChart"  :options="chartOption" :ref="'pie'" :auto-resize="''"></EChart>
处成功解决。

**Comment by Justineo** [comment]
需要在弹窗显示之后才渲染吧，否则取不到尺寸呀。
