### ISSUE TITLE
关于vue-echarts中echarts的版本问题

### ISSUE THREAD

**Issue by palmerye** [Justineo/vue-echarts#108]
现在echarts最新版本为3.6.2，但readme里写到依赖的echarts版本为3.3.2+，不知道Vue-echarts里的echarts版本为多少，因为考虑到3.3.2+之后版本迭代新增的feature及bug fixed。 
还请告知，谢谢 :)

**Comment by Justineo** [comment]
是这样的，我会定期同步 ECharts 的新增接口、事件的处理，但是没有更新依赖的版本。如果要用 3.3.2 以后新增的功能，可以直接用，但是需要安装对应版本的 ECharts。让我考虑一下，是否要把依赖的版本号改成最新。

**Comment by palmerye** [comment]
Thanks!

一点疑问,`需要安装对应版本的ECharts`
这个安装是通过什么方式?
是在`vue-echarts`的`dependencies`里手动更新`ECharts`版本号么?
还是说 `npm install ECharts`直接更新就行了?

关于版本号的一点建议:
- ECharts官网有个版本记录,你可以根据它的list做相对应的支持说明.

**Comment by Justineo** [comment]
你 `npm install echarts` 就可以用了。我刚搞错了，`package.json` 里的依赖已经是 `^3.6.0` 了。README 只是说了一个当时发布时 ECharts 的版本。
ECharts 的更新记录我就不重复写一遍了……
