### ISSUE TITLE
getZr is not a function

### ISSUE THREAD

**Issue by zhengtulymGh** [Justineo/vue-echarts#111]
引入了：
```
import ECharts from 'vue-echarts/components/ECharts' 

import 'echarts/lib/chart/scatter'

import 'echarts/lib/component/brush'

import 'echarts/lib/component/graphic'
```

在mounted里面：
```
let scatter = this.$refs.scatter

scatter.getZr().on('click', function(params) {

    console.log(params)

 })
```

报错：
`[Vue warn]: Error in mounted hook: "TypeError: scatter.getZr is not a function"`

**Comment by Justineo** [comment]
`getZr` 不是 ECharts 的公开 API，所以没有提供。你真的要使用的话，暂时可以使用 `this.$refs.scatter.chart.getZr()`。

**Comment by zhengtulymGh** [comment]
虽然不是vue-echarts的问题，但能否指导下怎么获取空白部分的坐标值？使用getZr()也是为了获取坐标值而进行监听的。
监听showTip只对有图形内容的地方起作用
```
myChart.on('showTip', function(params) {
    console.log(params)
 });
```

**Comment by zhengtulymGh** [comment]
我找到方法了，结合`getZr()`使用`convertFromPixel`就可以

**Comment by lijingyu1538** [comment]
@zhengtulymGh  能不能粘一下代码，参考一下，谢谢了

**Comment by LKK1535977706** [comment]
> @zhengtulymGh 能不能粘一下代码，参考一下，谢谢了

问题解决了吗，可以参考下吗
