### ISSUE TITLE
bar.showLoading() bar.mergeOptions()无法调用

### ISSUE THREAD

**Issue by zhipairen** [Justineo/vue-echarts#118]
按照 demo.vue中一步步调用，但是控制一直提示 showLoading 和 mergeOptions方法未定义，，
![image](https://user-images.githubusercontent.com/20217469/29919502-2e045dcc-8e7c-11e7-90f4-544bb448d1cf.png)

请问原因是什么呢？？

**Comment by Justineo** [comment]
目测你没有拿到组件的实例？

**Comment by zhipairen** [comment]
我严格按照  步骤一步步来的呀  怎么会这样呢？唯一的区别只是把 vue-echarts 通过局部引入的 不是全局组件，其他的 严格一步步来的呀  ，搞不懂

**Comment by Justineo** [comment]
有代码么？

**Comment by zhipairen** [comment]
发您私人邮箱了，麻烦看下

**Comment by Justineo** [comment]
请在 `<chart>` 上定义相应的 `ref`。
