### ISSUE TITLE
如何使用 Echarts实例中的方法，比如 convertToPixel 等

### ISSUE THREAD

**Issue by NeilJee** [Justineo/vue-echarts#12]
你好，我想把 http://echarts.baidu.com/demo.html#line-draggable 这个例子改写成vue的，但拿过来之后不知道如何使用实例中发方法。看了其他issue，使用v-ref来引用子组件的实例，但我再控制台看了一下，子组件实例中似乎也没有这些方法。  

可以帮忙看下么

**Comment by Justineo** [comment]
`convertFromPixel` 这个方法是 `3.3.0` 新加的，这各项目写的时候还没有，所以还没有把它桥接出来。

**Comment by Justineo** [comment]
在 `2.0.0` 中已加入相关接口，不过依赖的版本也升级到了 `2.0.1`。
