### ISSUE TITLE
dataZoom如何使用？

### ISSUE THREAD

**Issue by Zen33** [Justineo/vue-echarts#120]
在 options中使用dataZoom，并不显示，求助。

**Comment by Zen33** [comment]
原来是木有引入component，已解决。

**Comment by jasonlam-swatow** [comment]
@Zen33 Hi，请问你怎么实现 dataZoom 的？

**Comment by Zen33** [comment]
@jasonlam-swatow , import 'echarts/lib/component/dataZoom'
