### ISSUE TITLE
这几行代码有什么作用？

### ISSUE THREAD

**Issue by iamwelk** [Justineo/vue-echarts#122]
![image](https://user-images.githubusercontent.com/6983075/30156877-6ed43850-93f3-11e7-92be-8f7f5796ff21.png)

如上图，不明白这几个方法要怎么使用？为什么不放到methods里面呢？

**Comment by Justineo** [comment]
这些是静态方法。Demo 里面有。

**Comment by iamwelk** [comment]
好的，谢谢！
