### ISSUE TITLE
请问我想通过点击一个按钮上调用mergeOptions（）方法来改变series.data，参照Echarts3.0的setOption（）方法，为什么没效果呢？

### ISSUE THREAD

**Issue by renruijun** [Justineo/vue-echarts#123]
我想通过点击一个按钮上调用mergeOptions（）方法来改变series.data，参照Echarts3.0的setOption（）方法，为什么没效果呢？代码如下：
![image](https://user-images.githubusercontent.com/28946184/30264220-7a25f044-970a-11e7-9748-c4be7992d04a.png)
这样传参对吗（我是将整个options传进去），应该怎么传？

**Comment by Justineo** [comment]
组件实例已经 `deep` `watch` 了 `options`，如果修改 `options` 应该是会直接调用 ECharts 的 `setOption` 的。你可以暂时先试试 `this.$refs.warnLine.chart.setOption(this.polar)` 看看有没有效果，这个相当于直接调用 ECharts 实例的方法。如果依然无效，那么可能是你的数据更新写得不对。

**Comment by renruijun** [comment]
好的，我试一下，另外有没有vue-echarts的详细文档地址呢？各方法和参数有举例的那种？

**Comment by Justineo** [comment]
除了 `mergeOptions`，其他都和 ECharts 本身的接口一样。

**Comment by renruijun** [comment]
好，谢谢啦，并且刚刚的问题也解决了已经。
