### ISSUE TITLE
呃，作者大大，提一个很弱鸡的问题，为什么我的配置项里面的title不起作用？(why my 'title' in 'options' 不起作用？英语不好，贱笑了。。。)

### ISSUE THREAD

**Issue by renruijun** [Justineo/vue-echarts#124]
我配置在options里面的title属性没有起作用，请问什么原因，我真的自己有找了好久，可是还是没发现原因，代码如下：
![image](https://user-images.githubusercontent.com/28946184/30268785-6b5ba37e-9719-11e7-85c1-2d8b98a9cef3.png)
效果如下：
![image](https://user-images.githubusercontent.com/28946184/30268810-89e3a9fe-9719-11e7-9ed2-380ec4bc4ca7.png)

**Comment by Justineo** [comment]
```js
import 'echarts/lib/component/title'
```
