### ISSUE TITLE
请问下  vue-echarts 支持的vue版本是多少啊？ @2.1.6吗？ 升级了vue版本好像就会报错

### ISSUE THREAD

**Issue by Angelsindevil** [Justineo/vue-echarts#125]
![image](https://user-images.githubusercontent.com/28974350/30305791-6b85f00a-97a7-11e7-8b23-9351250d1812.png)

![image](https://user-images.githubusercontent.com/28974350/30305786-579eae60-97a7-11e7-9379-1761f5b48bcb.png)

**Comment by Justineo** [comment]
这个和本项目无关。请认真阅读报错信息，你需要的都已经在里面了。`vue` 的版本需要和 `vue-template-compiler` 一致。
