### ISSUE TITLE
关于setOption的效率问题。

### ISSUE THREAD

**Issue by dongsir** [Justineo/vue-echarts#126]
关于setOption，官方文档中有提到notMerge 这个参数，vue-echarts将其直接设置为了true,是否会有效率上的问题？

>chart.setOption(option, {
    notMerge: ...,
    lazyUpdate: ...,
    silent: ...
});
option
图表的配置项和数据，具体见配置项手册。
notMerge
可选，是否不跟之前设置的option进行合并，默认为false，即合并。
lazyUpdate
可选，在设置完option后是否不立即更新图表，默认为false，即立即更新。

**Comment by dongsir** [comment]
options: {
      handler (options) {
        if (!this.chart && options) {
          this.init()
        } else {
          **this.chart.setOption(this.options, true)**
        }
      },
      deep: true
    },

@Justineo  this.chart.setOption(this.options, true)  中 notMerge 这个参数是不是可以指定会更好呢？

**Comment by Justineo** [comment]
这个只影响通过赋值操作修改 `options` 的情况。设想用户按如下的方式操作：

```vue
<template>
  <div>
    <chart :options="options"/>
    <button @click="fetchData">
  </div>
</template>

<script>
import Chart from 'vue-echarts/component/ECharts'
import { requestData } from './remote'

export default {
  components: {
    Chart
  },
  data () {
    return {
      data: null
    }
  },
  computed: {
    options () {
      // convert data to options
      return { /* ... */ }
    }
  },
  methods: {
    fetchData () {
      // fetch from server
      requestData().then(data => {
        this.data = data
      })
    }
  }
}
</script>
```

这个时候每次 `options` 返回的都是新对象，如果用 `notMerge: false` 的话，其实语义是错误的。如果你的确需要 merge，你可以直接调用实例上的 `mergeOptions` 方法（等价于 ECharts 的 `setOption`，只是为了接口语义更明确，更符合默认情况，做了修改）。
