### ISSUE TITLE
定义的 _init 函数会导致 vuejs 报warning

### ISSUE THREAD

**Issue by wh1100717** [Justineo/vue-echarts#127]
WARNING:

```
[Vue warn]: Method "_init" conflicts with an existing Vue instance method. Avoid defining component methods that start with _ or $.
```

vue: 2.4.3
vue-echarts: 2.4.0

**Comment by Justineo** [comment]
Thanks!

**Comment by Channely** [comment]
老餮 刚看到这一幕的瞬间 我都有了打“赏”你的冲动 然后手机还没掏出来 打“伤”你的想法就占据了高地 周末就差没把node_moudles拆了  靠无意中联想到charts数和报错数的关系 才开始怀疑是这环出了问题

最后 感谢你滴贡献 还有办事效率 O。O

**Comment by hellodigua** [comment]
@Channely 咱们的新项目也遇到这个问题了，我搜着搜着，怎么就看到你了……

**Comment by Channely** [comment]
正所谓 _**狭路相逢**_
