### ISSUE TITLE
组件里的_init 方法好像和VUE的方法冲突了

### ISSUE THREAD

**Issue by icssjs** [Justineo/vue-echarts#128]
[Vue warn]: Method "_init" conflicts with an existing Vue instance method. Avoid defining component methods that start with _ or $.

    "vue": "^2.4.4",
    "vue-echarts": "^2.4.0",

**Comment by icssjs** [comment]
好像是出现在vue 2.4.4这个版本，我用的2.3.4是没有问题的

**Comment by Justineo** [comment]
和 #127 相同，请升级到 v2.4.1，此问题已经修复。
