### ISSUE TITLE
页面多个图表

### ISSUE THREAD

**Issue by wanghuai123** [Justineo/vue-echarts#13]
如果页面上面有多个图表 使用这个应该怎么弄，
![image](https://cloud.githubusercontent.com/assets/24269707/20750337/376a1a8c-b731-11e6-8092-023e5b60747e.png)  第二个div里面的数据不会渲染 应该怎么弄好

**Comment by Justineo** [comment]
你参考下项目的 demo，里面一个页面本来就有多个图表。

**Comment by wanghuai123** [comment]
![image](https://cloud.githubusercontent.com/assets/24269707/20751853/2421e254-b739-11e6-9388-3396376b12da.png)
我想问下 这里面这两个是代表什么，看的不是很懂 能给我解释一下么 非常感谢

**Comment by wanghuai123** [comment]
![image](https://cloud.githubusercontent.com/assets/24269707/20751876/3c22d46c-b739-11e6-860a-8013a5a77048.png)

**Comment by Justineo** [comment]
ECharts 的配色主题。

**Comment by wanghuai123** [comment]
还有一个小问题  这两个图表是放在tab选项卡里面的，在做切换的时候， 第二个图表他不会生效 
![image](https://cloud.githubusercontent.com/assets/24269707/20787204/9e7a0638-b7e5-11e6-86f3-b9664cd4045f.png) 直接在页面上面放两个图表是好的

**Comment by Justineo** [comment]
这个可能是你在隐藏状态下初始化 ECharts 的问题，和这个 Vue 组件的逻辑应该没有关系。
