### ISSUE TITLE
new echarts.graphic.LinearGradient此类方法如何执行？

### ISSUE THREAD

**Issue by Zen33** [Justineo/vue-echarts#130]
谢谢。

**Comment by Justineo** [comment]
请参考 Demo 李的代码。

https://github.com/Justineo/vue-echarts/blob/a272a3bd3bbc542cdb0c4a6df09fb2c120068879/demo/data/scatter.js#L320-L328

**Comment by Zen33** [comment]
感谢这么快的回复~
