### ISSUE TITLE
this demo is not support, is it because version older?

### ISSUE THREAD

**Issue by llccing** [Justineo/vue-echarts#134]
### Expected Behavior

![image](https://user-images.githubusercontent.com/12945329/31005098-d4c156e2-a529-11e7-8713-ab658c1f1659.png)

### Actual Behavior

![image](https://user-images.githubusercontent.com/12945329/31005114-e78fa2ba-a529-11e7-887c-814bf1ca0553.png)

this is demo from [Echarts Examples](http://echarts.baidu.com/demo.html#pie-nest)

### Environment
- vue.js version: 2.4.2
- vue-echart.js version: 2.4.1
- npm version: 5.3.0

i find this repo include the ECharts is 3.6.0, and latest version 3.7.2,  the problem i ask, is a new featrue. 
should i update the echarts version.  first i should clone this project, and recomplile? 

please give me some direction， thanks

**Comment by Justineo** [comment]
To use latest version of ECharts, you should import the source version of this component which is `vue-echarts/components/ECharts`.

**Comment by llccing** [comment]
should I update my project node_modules/ vue-echarts/, can you show me details

**Comment by Justineo** [comment]
Install latest version of `echarts` in your local project and follow the instructions in the README, and load the source version of Vue-ECharts so that it won't use the bundled ECharts lib of an older version.
