### ISSUE TITLE
引入'echarts/lib/component/markPoint' 或者 markLine markArea 报错

### ISSUE THREAD

**Issue by dongsir** [Justineo/vue-echarts#135]
只要引入上述三个组件的任意一个，就会提示错误（即使在Options中并没有用到markPoint markLine）

报错信息：
[Vue warn]: Error in mounted hook: "Error: Option should contains series."
[Vue warn]: Error in callback for watcher "options": "Error: `setOption` should not be called during main process."

**Comment by Justineo** [comment]
你是怎么引入组件的呢？

**Comment by dongsir** [comment]
import ECharts from 'vue-echarts/components/ECharts';
import 'echarts/lib/chart/bar';
import 'echarts/lib/chart/line';
import 'echarts/lib/component/markPoint';
import 'echarts/lib/component/tooltip';
@Justineo

**Comment by dongsir** [comment]
应该是这三个组件需要初始数据引起的问题，解决了。
你可以关闭这个问题了。

另外这个问题考虑实现一下吗？https://github.com/Justineo/vue-echarts/issues/126
