### ISSUE TITLE
不支持柱状图的柱子上的数字标签的旋转角度

### ISSUE THREAD

**Issue by jocongmin** [Justineo/vue-echarts#136]
series: [
{
			name: "demo",
			type: 'bar',
			label: {
				normal: {
					rotate:45,//这个rotate不支持，请问怎么办
					show: true,
					position: 'top',
				}
			},
			data: ...,
		}
]

**Comment by Justineo** [comment]
用的什么版本的 ECharts？怎么引入的组件？

**Comment by jocongmin** [comment]
引入echart的方式是
import ECharts from "vue-echarts";
Vue.component('chart', ECharts)

我觉得这个问题不是引入问题，应该是echart的版本问题，不知道你这个组件怎么升级echarts到最新版本呢

**Comment by jocongmin** [comment]
@Justineo 引入echart的方式是
import ECharts from "vue-echarts";
Vue.component('chart', ECharts)

我觉得这个问题不是引入问题，应该是echart的版本问题，不知道你这个组件怎么升级echarts到最新版本呢？我已经重新安装过你的组件到最新版本了，不过好像echart的版本好像还是落后官网的版本，不知道怎么升级你组件背后的echarts到最新的版本呢

**Comment by Justineo** [comment]
用打包好的版本是会有这个问题，建议使用源码方式引入。README 里面有详细描述的。

**Comment by jocongmin** [comment]
@Justineo  解决了，应该是已经打包的这个图表组件不是最新的吧，所以直接源码导入和编译会是最新的echarts功能

**Comment by Justineo** [comment]
恩，这样自己去按需加载 ECharts 的各个子组件也会让最后的 bundle 更小。
