### ISSUE TITLE
直接import组件非打包的不能title不能出现？

### ISSUE THREAD

**Issue by jocongmin** [Justineo/vue-echarts#138]
表格的题目没有出现，可是用打包的可以，用webpack编译组件的不行

**Comment by Justineo** [comment]
要自行引入 ECharts 相关的模块。打包版本的 ECharts 引入的模块可以参见[这里](https://github.com/ecomfe/echarts/blob/master/index.js)。

比如里面是这么引入你需要的 `title` 功能的：

```js
require('./lib/component/title');
```

那么在你的项目里，就要：

```js
import 'echarts/lib/component/title'
```
