### ISSUE TITLE
nuxt 引入vue-echarts 刷新时会报错

### ISSUE THREAD

**Issue by EasonShen1989** [Justineo/vue-echarts#139]
[Vue warn]: The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup, for example nesting block-level elements inside `<p>`, or missing `<tbody>`. Bailing hydration and performing full client-side render

**Comment by EasonShen1989** [comment]
最近版本 nuxt 加入了`<no-ssr></no-ssr>`解决了这个问题

**Comment by Justineo** [comment]
那我先关闭了。
