### ISSUE TITLE
请问，按照您这个步骤引入后，出现报错

### ISSUE THREAD

**Issue by xjccc** [Justineo/vue-echarts#144]
错误信息： Error: Component series.pie not exists. Load it first.
这个应该怎么解决呢？

**Comment by Justineo** [comment]
你需要自己引入用到的 ECharts 对应的模块。比如：

https://github.com/Justineo/vue-echarts/blob/9d41b2772084a5a8e560aecfe157c609ca30a234/demo/Demo.vue#L252-L265

**Comment by xjccc** [comment]
好的。谢谢~！

**Comment by xjccc** [comment]
@Justineo 请问，可以显示城市点的那个地图，如何清除之前的data呢？我请求新的接口，mergeOptions后，前面的数据还会重复显示

**Comment by Justineo** [comment]
@xjccc 你可以直接重新给 `options` 这个 prop 赋值。或者给 `mergeOpitons` 传参数：`notMerge: true`（参考 ECharts 的 `setOption`）。

**Comment by xjccc** [comment]
之前也有写这个值。。传了这个值。。然后出现这个错误 ：Error: series.type should be specified.
this.$refs.map.mergeOptions(o, { notMerge: true })   这样传的。。

**Comment by Justineo** [comment]
你看一下你那个 `o` 里的数据对不对？

**Comment by xjccc** [comment]
[name:'海门',value:[0: 121.15, 1: 31.89, 2: '1321' , 3: '我的天']]   这样的数据结构。。

**Comment by Justineo** [comment]
你到底要覆盖还是不要覆盖……需要设置完整的 `options` 呀。

**Comment by xjccc** [comment]
需要覆盖。。。。这个o不是我的数据吗。。。。

**Comment by Justineo** [comment]
`Error: series.type should be specified.` 所以错误不是已经提示你了么？格式不对啊。

**Comment by xjccc** [comment]
我现在接口返回的是省份。
但是我用的是您那个城市相关的数据。
然后设置我的options是
`dataTemp.forEach((item, index) => {
    // 将接口返回的tel和name添加到value中
          dataTemp[index].value = [_Data[index].tel, _Data[index].name]
        })
this.mapData = this.convertData(dataTemp)
let o = {
          series: [
            {
              data: this.mapData
            }
          ]
        }
this.$refs.map.mergeOptions(o)
`
然后我想过1个小时再调用一次这个方法。但是，第一次请求的数据，他还存在。第二次请求的数据，他会从第一个海门开始。

**Comment by Justineo** [comment]
你把整个 `o` 打出来嘛……

**Comment by xjccc** [comment]
{series: Array(1)}
series:Array(1)
0
:data:Array(190)
[0 … 99]     // [name:'海门',value:[0: 121.15, 1: 31.89, 2: '1321' , 3: '我的天']] 
[100 … 189]
length:190
__ob__:Observer {value: Array(190), dep: Dep, vmCount: 0}
__proto__:Array
type:"scatter"

打印出来。。就是这样的。。。

**Comment by Justineo** [comment]
所以说你传入的数据本身就不对啊……这本身就和本项目无关了。你需要自己处理好对象引用，而不是把同一个对象不断进行修改。

**Comment by xjccc** [comment]
就是我再次请求的时候。。走一下赋值方法。。不是应该把这个值改变应该就可以了吗。那我应该传入什么数据呢。。有点没有搞明白。。

**Comment by Justineo** [comment]
你传入的数据应该是一个全新的对象啊。

**Comment by xjccc** [comment]
是全新的啊。。。不是应该把上次的覆盖了吗。。就是类似数据没有覆盖掉。。所以出现错乱了。。然后我想设置notmerge。。一设置。。就报错了。。是不是应该清除上次数据之类的

**Comment by Justineo** [comment]
全新的里面哪来的 ob 属性……

**Comment by xjccc** [comment]
0 0.因为确实现在我用的数据是一样的。。只有一个小时才会变化。。。
