### ISSUE TITLE
echarts 3.8 changed export

### ISSUE THREAD

**Issue by Maopy** [Justineo/vue-echarts#145]
there is no `module.exports = echarts` in echarts version 3.8, so vue-echarts will get an error

**Comment by Justineo** [comment]
I'm discussing a solution with ECharts team. You can keep using 3.7 for now.

**Comment by Maopy** [comment]
由于 vue-echarts 依赖的是 ^3.x，所以安装的时候默认就选择了 3.8 版本的 echarts，这个目前有办法解决么？

**Comment by Justineo** [comment]
自己项目的 package.json 里锁死版本吧

**Comment by Justineo** [comment]
ECharts 发布了新版本解决了这个问题，我们只要跳升一下依赖就可以了。

目前安装 `vue-echarts@2.5.1` 即可解决问题。
