### ISSUE TITLE
echarts 刚更新3.8.3了  这个是不是要更新下？

### ISSUE THREAD

**Issue by hank2718** [Justineo/vue-echarts#148]
![image](https://user-images.githubusercontent.com/7368299/32654047-da7111e0-c644-11e7-8a8d-5f91aa2f59f6.png)
![image](https://user-images.githubusercontent.com/7368299/32654073-ec4fa426-c644-11e7-8e0b-fa6e4ded0ecb.png)

**Comment by orangle** [comment]
我这里默认的依赖也是 2.x echarts版本

**Comment by fangzhioo** [comment]
I want to use map with vue-echarts！
but echarts v3+ without internal map !   eg: china.js..
How to add map in it？

**Comment by Justineo** [comment]
@fangzhioo There **is** a static method `registerMap`. See https://github.com/Justineo/vue-echarts#static-methods.

**Comment by Justineo** [comment]
`vue-echarts@2.6.0` 现在依赖 `echarts@^3.8.5`.
