### ISSUE TITLE
怎么添加map的相关js

### ISSUE THREAD

**Issue by fangzhioo** [Justineo/vue-echarts#149]
echarts v3+之后，没有内置map了，需要引入地图相关的js，如：china.js 等。
在使用vue-echarts时，就出现了地图没有的情况，请问怎么将这些地图的js引入？
我试过直接引入js，但是报错！大致意思是，没有找到Echarts。。

**Comment by Justineo** [comment]
你这样提问没有任何帮助，这个项目的 demo 里有引入地图的例子。

请仔细阅读 README 并参考：https://github.com/Justineo/vue-echarts/blob/master/demo/Demo.vue

**Comment by fangzhioo** [comment]
不好意思 没看见这个demo。。 
解决了 谢谢~
