### ISSUE TITLE
IE

### ISSUE THREAD

**Issue by atomjaylee** [Justineo/vue-echarts#15]
这个插件在IE浏览器下打不开。。。。。。

**Comment by Justineo** [comment]
[Demo](https://justineo.github.io/vue-echarts/demo/) 在 IE 下可以正常运行，不清楚你的环境是什么样的。

**Comment by forleve** [comment]
DEMO在IE 11下打不开

SCRIPT5022: [vuex] vuex requires a Promise polyfill in this browser.

**Comment by Justineo** [comment]
@forleve 后来在 demo 里加了 Vuex 的示例。在 IE 不支持原生 Promise，需要自己引入一个 polyfill。
