### ISSUE TITLE
[建议] 增加对echarts GL的支持

### ISSUE THREAD

**Issue by ultraN** [Justineo/vue-echarts#150]
配置和Api相似，实现难度应该不大。
[echarts gl](https://github.com/ecomfe/echarts-gl)

**Comment by Justineo** [comment]
直接用就可以了吧，这里应该不需要增加支持的。

**Comment by ultraN** [comment]
https://github.com/Justineo/vue-echarts/blob/38f8f9602ca9d6bffdce69b8a9fbe91c1f63a741/src/components/ECharts.vue#L13

https://github.com/Justineo/vue-echarts/blob/38f8f9602ca9d6bffdce69b8a9fbe91c1f63a741/package.json#L19

依赖和组件载入的引入里都没有echarts-gl，这是echarts的另外一个包。

**Comment by Justineo** [comment]
这个本来就是让你自己引入的。

**Comment by Justineo** [comment]
这个本来就是让你自己引入的。

**Comment by ultraN** [comment]
我尝试用import 和 require导入echarts-gl都失败了
require('echarts-gl') or import 'echarts-gl'
报错：
Uncaught ReferenceError: __DEV__ is not defined
    at eval (geo3DCreator.js?8429:92)
    at Object.<anonymous> (app.js:3691)
    at __webpack_require__ (app.js:679)
    at fn (app.js:89)
    at eval (geo3D.js?0e61:6)
    at Object.<anonymous> (app.js:8439)
    at __webpack_require__ (app.js:679)
    at fn (app.js:89)
    at eval (index.js?396a:4)
    at Object.<anonymous> (app.js:7529)

查了下echarts-gl的issues里面也有这个[问题](https://github.com/ecomfe/echarts-gl/issues/140)。

**Comment by Justineo** [comment]
你暂时可以修改你的 webpack 配置，在 `ProvidePlugin` 里面新增一个 `DEV`。这个问题应该是 ECharts-GL 去修复的。

**Comment by MarcErdmann** [comment]
I included a webpack plugin as suggested. Unfortunately I get the following error:


**TypeError: viewGL.layer is null[Learn More]
app.js%20line%203796%20%3E%20eval:502:13
doLayout
GraphGLView.js:486
startLayout/<
GraphGLView.js:509**


followed by:


**TypeError: this.layer is null[Learn More]
app.js%20line%204076%20%3E%20eval:152:9
ViewGL.prototype.containPoint
ViewGL.js:139
_mouseDownHandler
Roam2DControl.js:108
_mouseDownHandler self-hosted:976:17 trigger
Eventful.js:158
dispatchToElement
Handler.js:218
Handler.prototype[name]
Handler.js:292
trigger
Eventful.js:158
domHandlers[name]
HandlerProxy.js:218
makeMouseHandler/<
HandlerProxy.js:245**
