### ISSUE TITLE
怎么使用词云图？

### ISSUE THREAD

**Issue by fangzhioo** [Justineo/vue-echarts#152]
3+之后就没有word-cloud词云图了，
看作者大大的Demo也没有涉及到词云图，
可是我希望在用vue-echarts的同时，
也可以使用之前版本的词云图，该怎么做啊？

**Comment by Justineo** [comment]
https://github.com/ecomfe/echarts-wordcloud

这不是有吗？

**Comment by swuecho** [comment]
@fangzhioo  找到方案了么？

@Justineo 链接里面只有如何与eschart 进行整合，不知道怎么与vue eschart 进行整合。

**Comment by Justineo** [comment]
@swuecho 一样的，不需要额外的操作。

**Comment by swuecho** [comment]
多谢 @Justineo 

已验证 如下可以显示，

```
import echarts from 'echarts';
import ECharts from "vue-echarts/components/ECharts";
import "echarts-wordcloud"
```
