### ISSUE TITLE
热力图数据量较大时导致浏览器崩溃

### ISSUE THREAD

**Issue by divanodestiny** [Justineo/vue-echarts#153]
使用的是官方实例里面的[热力图demo](http://echarts.baidu.com/demo.html#heatmap-large-piecewise)，仅将`option =`改为`default export ` , 加载速度尚可，但是加载完成之后页面出现明显的卡顿，切换路由在数据量是200\*100的时候会导致页面崩溃，数据量是50\*50是不会崩溃，但是切换路由速度仍十分缓慢，切换路由钱需要手动通过merge一个空的数据集才不会卡住，但是看echart的官方demo并没有出现问题，疑似vue-echarts热力图优化存在问题

**Comment by Justineo** [comment]
可能是因为 deep watch 的原因。可能需要在初始化的时候给个选项来确定是否要做 deep watch。

**Comment by Justineo** [comment]
`vue-echarts@2.6.0` 增加了一个 prop `watchShallow`，设置为 `true` 则不会 deep watch `options`。相应地，需要修改时也需要改变整个 `options` prop 的引用。除此之外也可以通过 `$refs` 获取示例以后，手动调用 `mergeOptions` 来修改数据。

这个属性是否能解决这个问题，如有测试过麻烦告知一下结果，谢谢！

**Comment by ntutangyun** [comment]
" 相应地，需要修改时也需要改变整个 options prop 的引用。   "

是什么意思 ??

**Comment by Justineo** [comment]
就是 `oldValue !== newValue` 的意思。比如把原来的 options 浅拷贝一下后重新设置。

**Comment by Justineo** [comment]
先关闭了，如仍有问题请 reopen。

**Comment by ly525** [comment]
@Justineo 

版本信息如下：
 "echarts": "^4.1.0",
"vue": "^2.2.6",
"vue-echarts": "^3.0.9",


我们在真实场景中测试了，watchShallow 没有生效，options 中的各种选项仍然被 Vue watch 了，导致内存泄露，在crash的地方，很明显的看到是 walk 方法那里。walk 的obj 很明显不是我们想要的，几乎都是 echarts 的 options。

同样的 line chart（每条线上96个点个点，一个图上 4条线，x轴 96个点，总共 480 个点），996 个图（332行 * 3 ）， 使用vue-charts 绘制，在滚动到 15个图左右的时候，内存很快到达1500MB，再向下滚动，内存泄露了。

改成获取 dom 节点，然后使用 echarts 进行 init 之后，做setOptions 之后，996 个图，最终占用内存稳定在 960M 上下。

但具体究竟是哪里的写法导致内存泄漏，我们怀疑是 created 中对 options的 watch 导致的，但是再详细的探究，我们现在还没有做。
我会先把手里的需求实现之后，把这个问题做一下仔细研究的，内存泄漏的问题太困扰自己了

**Comment by Justineo** [comment]
我想了一下，的确没有生效，如果要彻底去除 watch，应该是完全不通过 `options` prop 来操作组件。

你可以先尝试一下这样做：

1. 不给组件传 `options` prop；
2. 父组件 `mounted` 以后通过 `$refs` 获取组件实例，手动调用 `init()` 方法（暂时先这样处理，这个接口以后不会暴露出来，可能会自动在实例方法被调用时去初始化）；
3. 之后手动调用组件实例的 `mergeOptions` 方法来更新 ECharts 实例。

当然，这样做和直接接入 ECharts 已经没有什么区别了。

**Comment by ly525** [comment]
@Justineo 我们现在的方案和您说的几乎一模一样了，先放一个空的占位符，然后滚动到屏幕可见的时候，再refs 获取组件，做init 操作，再做mergeOptions。
不过还是从您的组件库里面学习到很多内容，非常感谢

**Comment by Justineo** [comment]
@ly525 `initOptions` 不是图表数据本身，`options` 才是。
