### ISSUE TITLE
官方实例，提示Component series.line 不存在？

### ISSUE THREAD

**Issue by cfanbo** [Justineo/vue-echarts#154]
vue版本2.5.8 webpack 2.6.1  EChart3.8.2
Error: Component series.line not exists. Load it first.

**Comment by chping2125** [comment]
@cfanbo 我今天在使用 webpack externals 拆 echarts 时，也报了这个错，是什么原因？

**Comment by alwxkxk** [comment]
`import 'echarts/lib/chart/line'`
