### ISSUE TITLE
改变数据后，图上的legend会消失

### ISSUE THREAD

**Issue by 294007813** [Justineo/vue-echarts#157]
初始的options能显示legend，改变数据后，legend属性没变，但是图上的legend却消失了。

**Comment by Justineo** [comment]
缺乏必要的信息，无法提供帮助。请先确认是否在 ECharts 中无此问题。

**Comment by 294007813** [comment]
就是我用 :options绑定一个初始option是正常的，然后我改变了option里面的series的data值，图例数值变化后，不知道为啥图例的legend却不显示了，
 ECharts中确实无此问题

**Comment by 294007813** [comment]
不好意思，这个是ECharts中存在的问题
