### ISSUE TITLE
vue-cli采用的是webpack-simple搭建的脚手架，配置相关的loader就不在这个范围类

### ISSUE THREAD

**Issue by chenqing2016** [Justineo/vue-echarts#159]
在引入vue-echart之是可以实现打包的，但是引入之后总是报ERROR in build.js from UglifyJs
Unexpected token: punc ()) [./node_modules/_vue-echarts-v3@1.0.17@vue-echarts-v3/src/wrapper.js:43,0][build.js:53557,18]
我知道是压缩错误，可是我试了很多种方式，都解决不了这个问题，匹配js的本身代码如下：    
  {
        test: /\.js$/,
        loader: 'babel-loader',
          exclude: /node_modules/
      },
想请问一下，解决这个问题

**Comment by Justineo** [comment]
请仔细阅读 [README](https://github.com/Justineo/vue-echarts#importing-the-souce-version)。
