### ISSUE TITLE
webpack 打包后IE浏览器无法浏览

### ISSUE THREAD

**Issue by atomjaylee** [Justineo/vue-echarts#16]
之前的问题后来发现不是插件的问题，但是当使用vue-cli等脚手架开发页面，使用插件时，执行`npm run dev`时，在谷歌浏览器是正常的，但是在IE下是无法查看的，这个有解决方案吗

**Comment by Justineo** [comment]
https://github.com/Justineo/vue-awesome/issues/7#issuecomment-255550674
有按这个改过么？

**Comment by Justineo** [comment]
因为没有反馈，我先关闭了，如有问题继续回复即可。
