### ISSUE TITLE
liquidfill renderer 不支持svg

### ISSUE THREAD

**Issue by ntutangyun** [Justineo/vue-echarts#161]
我尝试用liquidfill 画了三张图，然后 尝试用 initOptions="{renderer: 'svg'}" 结果画出来还是在 canvas tag里面。

**Comment by Justineo** [comment]
这个问题请提给 [ecomfe/echarts-liquidfill](https://github.com/ecomfe/echarts-liquidfill) 吧。

**Comment by langgo** [comment]
```js
import 'zrender/lib/svg/svg';
```
