### ISSUE TITLE
question: registering without using "import"

### ISSUE THREAD

**Issue by laudena** [Justineo/vue-echarts#162]
Hi, 
Is it possible to register the component without using a transpiler?
What component name should I be using?

my question is similar to the one in the following thread: 
[Can I register a third party component without importing it](https://forum.vuejs.org/t/can-i-register-a-third-party-component-without-importing-it-from-my-server/4356)

Thanks on advance

**Comment by Justineo** [comment]
Currently Vue-ECharts only provides the uncomipled source and the all-in-one UMD bundle on npm.

The UMD bundle can be used directly without transpiler:

```js
// for CommonJS
var ECharts = require('vue-echarts')
```

**Comment by laudena** [comment]
thanks a lot!!!
