### ISSUE TITLE
demo正常，npm安装成功之后引用legend的type的scroll属性，报错误不存在！

### ISSUE THREAD

**Issue by confidence68** [Justineo/vue-echarts#163]
demo案例正常，npm安装成功之后引用legend的type的scroll属性，报错误，组件不存在！
 Error in callback for watcher "options": "Error: Component legend.scroll not exists. Load it first.

```
legend:{
        show: true,
        type:"scroll",//plain普通图例
       data:data
    }
```

plain是正常的，就是scroll报错！

**Comment by Justineo** [comment]
```
Error: Component legend.scroll not exists. Load it first.
```

报错信息已经很明确了……

参考[这里](http://echarts.baidu.com/tutorial.html#%E5%9C%A8%20webpack%20%E4%B8%AD%E4%BD%BF%E7%94%A8%20ECharts)的**“按需引入 ECharts 图表和组件”**。
