### ISSUE TITLE
饼图的lenged根据不同的查询条件，显示当前的lenged

### ISSUE THREAD

**Issue by Mojie-Wang** [Justineo/vue-echarts#166]
`selected: {
    '1月3': true,
    '1月1': false,
    '1月2': false,
    '1月4': false,
}`
![demo](https://user-images.githubusercontent.com/20314455/34667377-b87846e8-f4a3-11e7-8756-353e12eb36cd.png)
![demo2](https://user-images.githubusercontent.com/20314455/34667599-a76d212e-f4a4-11e7-9a8a-800b94284f15.png)

**Comment by Justineo** [comment]
这是你自己的业务逻辑吧……和这个项目有什么关系……

**Comment by Mojie-Wang** [comment]
我是想说可以根据不同的筛选条件，显示lenged里的不同item， 上面贴的图片是举例子
