### ISSUE TITLE
关于dispose之后如何再次初始化

### ISSUE THREAD

**Issue by 759325100** [Justineo/vue-echarts#167]
我发现echarts动态更新存在内存泄漏，包括水球图在内，作者也都认可这个问题，现在我想要页面运行一段时间后，使用实例的dispose方式进行销毁，然后在进行重新init，但是我不清楚应该怎么重新init这个实例对象。官方使用的是echarts.init(xxx)。
销毁代码
```
this.$refs.devicePie.dispose()
// 这里如何进行init
????
```
除了进行dispose外，clear不清楚是否会具有同样的效果，还待测试。

**Comment by Justineo** [comment]
Vue-ECharts 实例上提供了 `refresh` 方法，可以销毁后重新初始化。但这个是一个内部使用的方法，没有写在 API 文档里。（因为理应不需要用户手动刷新）

你可以先用这个方法刷新解决眼前的问题。

**Comment by 759325100** [comment]
好的，我会进行尝试。对您的支持表示感谢 ~
