### ISSUE TITLE
group属性怎么使用？

### ISSUE THREAD

**Issue by yyzph** [Justineo/vue-echarts#17]
如题，group的对象格式是怎样的？

**Comment by Justineo** [comment]
这个和 ECharts 的接口是一致的，只是把 ECharts 的 get 和 set 接口用一个带 getter/setter 的属性代替了。看 ECharts 的文档吧。

**Comment by yyzph** [comment]
// 分别设置每个实例的 group id
chart1.group = 'group1';
chart2.group = 'group1';
echarts.connect('group1');
// 或者可以直接传入需要联动的实例数组
echarts.connect([chart1, chart2]);

**Comment by yyzph** [comment]
// 分别设置每个实例的 group id
chart1.group = 'group1';
chart2.group = 'group1';
echarts.connect('group1');
// 或者可以直接传入需要联动的实例数组
echarts.connect([chart1, chart2]);


文档是这样关联的，group传的是字符串，vue-echats是object，然后我没有用option这个参数了，直接用的connect去关联

**Comment by Justineo** [comment]
应该并没有要求 `group` 是 Object 呀？

**Comment by yyzph** [comment]
明白了~我用的是vue2-charts~我看到你给他的回复了
