### ISSUE TITLE
动态加载数据时候，为什么图标的宽高大小会变化？

### ISSUE THREAD

**Issue by huangche007** [Justineo/vue-echarts#171]
当我给一个按钮设置点击事件的时候，图表的div首先是隐藏的，点击按钮的时候才显示图片，可是发现点击按钮显示的图表的大小宽度都变小了。

相关代码:

`  <li class="article-table-content-item article-table-content-item-detail" @click="openArticleContent(index)">
                          <span class="adv-data-sutuation">详情</span>
                          <i class="adv-op-icon"></i>
                        </li>`

` <div class="article-content-fenbu" style="margin-top: 20px;">
                        <p>分享数据</p>
                        <div class="table-r" style="width: 98%;">
                          <chart :options="option" ref="warnLine"></chart>
                        </div>
                      </div>`

`      let tOptions = {
              tooltip: {
                trigger: 'item',
                formatter: "{a} <br/>{b}: {c} ({d}%)"
              },

              color:['#83c9f7','#0bc337','#009900','#f3e970'],
              legend: {
                orient: 'vertical',
                x: 'right',
                data:['QQ','转发好友','朋友圈','QQ空间'],
                top: 70,
                left:500,
                bottom: 20,
                itemGap:30,
                textStyle:{    //图例文字的样式
                  color:'#959699',
                  fontSize:14
                }
              },
              graphic:{
                elements:[
                  {
                    type: 'text',
                    z: 2,
                    left: '18%',
                    top: '36%',
                    style: {
                      fill: '#1f2d3d',
                      textAlign:'center',
                      textVerticalAlign:'middle',
                      text: [
                        '573',
                        '阅读总数'
                      ].join('\n'),
                      font: '14px Microsoft YaHei'
                    }

                  }
                ],
              },
              series: [
                {
                  name:'访问来源',
                  type:'pie',
                  radius: ['40%', '55%'],
                  label: {
                    normal: {
                      formatter: '{per|{d}%}  ',
                      rich: {
                        a: {
                          lineHeight: 22,
                          align: 'center'
                        },
                        hr: {
                          width: '100%',
                          borderWidth: 0.5,
                          height: 0
                        },
                        b: {
                          fontSize: 16,
                          lineHeight: 33
                        },
                        per: {
                          color: '#8b8c8e',
                          backgroundColor: '#fff',
                        }
                      }
                    }
                  },
                  data:[
                    {value:310, name:'朋友圈'},
                    {value:234, name:'QQ空间'},
                    {value:135, name:'QQ'},
                    {value:1048, name:'转发好友'},
                  ],
                  center: ['22%', '38%'],
                }
              ],

            }
            this.option = tOptions;`

`openArticleContent(index){
          $(".article-content-detail").hide();
          $(".article-content-detail").eq(index).show();
          console.log("this.$refs.warnLine.chart:",this.$refs.warnLine[index]);
          this.$refs.warnLine[index].chart.setOption(this.option)
        },`

**Comment by Justineo** [comment]
请先保证容器已经显示出来了再初始化图表，或在容器显示后，手动调用组件实例的 `resize` 方法。

**Comment by huangche007** [comment]
@Justineo OK 谢谢

**Comment by fujiazhang** [comment]
thanks
