### ISSUE TITLE
Echarts 4.0 is released today

### ISSUE THREAD

**Issue by palmerye** [Justineo/vue-echarts#172]
Echarts 4.0 今天发布了.

有计划更新吗?

**Comment by Justineo** [comment]
有，马上就会发布新版本。

**Comment by 759325100** [comment]
期待升级到4.0。也希望能解决动态图表的内存占用问题（svg）

**Comment by Justineo** [comment]
> 也希望能解决动态图表的内存占用问题（svg）

解决这个问题就不在这个项目的范围之内了。

**Comment by palmerye** [comment]
@Justineo 给力! 

应该向下兼容ECharts 3.x 吧?

**Comment by Justineo** [comment]
@palmerye 可能要去掉一些 deprecated 的用法，以及可能会把 `auto-resize` 变成自动监听容器 resize 的方式。

**Comment by Creative6** [comment]
@Justineo 强啊!

**Comment by 759325100** [comment]
auto-resize确实存在问题，我都是在created里面自己再监听resize事件处理的。

**Comment by Justineo** [comment]
`+ vue-echarts@3.0.0`
