### ISSUE TITLE
coffee

### ISSUE THREAD

**Issue by royeaher** [Justineo/vue-echarts#173]
npm throw err "CoffeeScript on NPM has moved to "coffeescript" (no hyphen)"

**Comment by Justineo** [comment]
Where does this come from? What command were you trying to run?

**Comment by royeaher** [comment]
npm i

**Comment by Justineo** [comment]
Cannot reproduce the problem. Can you give more detailed information?

**Comment by royeaher** [comment]
Just because of coffeeScript`s repository had moved to another address.vue-cli had same issus and has fixed.

**Comment by Justineo** [comment]
OK, so I'm closing this one.
