### ISSUE TITLE
npm package missing .vue

### ISSUE THREAD

**Issue by SquareBeard** [Justineo/vue-echarts#174]
The npm package does not contain the .vue component file because the src folder is ignored in .npmignore
Could this be changed please ?
I'd like to keep using npm instead of downloading the source manually.

Thank you

**Comment by Justineo** [comment]
Isn't it available at `vue-echarts/components/ECharts.vue`?

**Comment by willsoto** [comment]
The `components` directory is no longer present in the repo. 
<img width="1007" alt="screen shot 2018-01-17 at 8 58 22 pm" src="https://user-images.githubusercontent.com/2791730/35077030-2f92e946-fbc9-11e7-906d-46cc5a434ae6.png">

**Comment by Justineo** [comment]
I see, I run the wrong publish command. This should be fixed in `v3.0.1`.
