### ISSUE TITLE
请教下如何在组件的宽高改变的时候组件自动重载画布呢

### ISSUE THREAD

**Issue by 419921017** [Justineo/vue-echarts#18]
我看到有个resize方法 是不是需要我在组件源码中修改些东西么?

**Comment by Justineo** [comment]
这个和 ECharts 本身是一致的，需要你监听全局的 `resize` 事件去手动调用。

**Comment by 419921017** [comment]
我刚刚修改了下您的代码 功能现在可以实现的 但是有个小问题 就是会有点卡呢 
我给您看下我的代码
我把本来在mouted里面的封装成了一个charInit 函数 引用了 一个 Vue

mounted() {
      var that = this
      var charResize = function(){
        that.resize()
      }
      Vue.nextTick( function(){
        that.charInit()
        if(window.attachEvent){
          window.attachEvent('onresize', charResize);
        }else{
          window.addEventListener('resize', charResize, false);
        }
      } )
    },

**Comment by Justineo** [comment]
卡顿的话自行节流，这个不是本项目需要处理的问题。请自己学习相关方法吧。
