### ISSUE TITLE
如何使用异步加载的数据渲染图表？

### ISSUE THREAD

**Issue by q27488** [Justineo/vue-echarts#2]
as this title，I wan to use Asynchronous loading to update my project, But I have trouble In this.
    Looking forward to your reply.（it will be better if you can use chinese!）
                                                                                                                            thanks.

**Comment by Justineo** [comment]
没事你直接用中文提问好了。

**Comment by q27488** [comment]
我想在我的vue工程中使用 echarts的异步加载数据，从后端API读取数据（已经实现），怎么让它更新进去呢？ 有没有类似demo，百度的教程不行啊。

**Comment by Justineo** [comment]
直接调用组件的 `mergeOptions(options)` 方法就可以了（ECharts 的 `setOptions(options)`）。

**Comment by Justineo** [comment]
ECharts 官方的文档有详细描述[异步数据](http://echarts.baidu.com/tutorial.html#%E5%BC%82%E6%AD%A5%E6%95%B0%E6%8D%AE%E5%8A%A0%E8%BD%BD%E5%92%8C%E6%9B%B4%E6%96%B0)的部分吧。

**Comment by q27488** [comment]
但是你的vue-echarts是用 :option = 'Mychart' 绑定数据，  而官方的需要 Mychart 这个ID的 echarts.init初始化得出的Object~

**Comment by Justineo** [comment]
增加了异步数据的 demo 代码，你可以看一下能否解决你的问题：https://github.com/Justineo/vue-echarts/blob/gh-pages/demo/Demo.vue

**Comment by q27488** [comment]
非常感谢，按照您的demo已实现功能，但是还存在一些BUG：异步加载后，echarts的legend属性失效了（不显示了）。  如果可以的话是否可以讲解一下this.$refs.bar.mergeOptions 与v-ref:bar的原理及使用； 因为我改成this.$refs.XXX.mergeOptions 及 v-ref:XXX 就报错： Cannot read property 'mergeOptions' of undefined。

**Comment by Justineo** [comment]
Vue.js 会把属性值做格式转换。只有 `v-ref:-x-x-x` 才会被转为 `$refs.XXX`。规则很简单，大写字母前加 `-` 然后转小写。反过来你在模板里定义的话就把 `-` 后面的字母转大写。比如 `v-ref:my-component` 在 JS 代码中引用就是 `$refs.myComponent`。

**Comment by q27488** [comment]
原来如此，怪不得我命名用驼峰法在vue的一些指令用不了(比如myComponent,只能全部小写mycompont才能用)，非常感谢你的指教。

**Comment by Justineo** [comment]
先关闭了。

**Comment by hpsoar** [comment]
如果没import theme，不显示legend，调了半天。

**Comment by huangyanxiong01** [comment]
3q
