### ISSUE TITLE
echarts map error

### ISSUE THREAD

**Issue by torresyb** [Justineo/vue-echarts#23]
![11](https://cloud.githubusercontent.com/assets/4061058/21516937/a639dfa2-cd15-11e6-811f-eba3665e666f.png)

**Comment by Justineo** [comment]
在 `demo` 里面增加了一个调用地图的例子。另外根据你的报错信息似乎很难定位问题呀。

**Comment by torresyb** [comment]
好的，我看看，谢谢了。

**Comment by Justineo** [comment]
@torresyb 问题是否解决了呢？

**Comment by torresyb** [comment]
谢谢，问题已经解决，我把visualMap放到mergeOptions({})中定义就好了。
