### ISSUE TITLE
请问如何实现渐变颜色呢

### ISSUE THREAD

**Issue by trionfo1993** [Justineo/vue-echarts#25]
使用echarts3的方式new echarts.graphic.LinearGradient 无法实现，如果引入util中的graphic又只能得到undefined

**Comment by Justineo** [comment]
你是用的打包版本还是源码版本？如果是打包版本（`require('vue-echarts')`）这样的，需要自己再引入 `echarts` 里相关的功能。如果是按 README 里推荐的方式，可以看一下项目 demo，我补充了相关的例子。

**Comment by trionfo1993** [comment]
谢谢

**Comment by renruijun** [comment]
请问想要像问题中那样使用这个渐变还需要引入哪个功能？？

**Comment by Justineo** [comment]
https://github.com/Justineo/vue-echarts/blob/master/demo/data/scatter.js

**Comment by renruijun** [comment]
好的，成了。谢了
