### ISSUE TITLE
y轴能去掉默认显示0-1刻度吗？

### ISSUE THREAD

**Issue by torresyb** [Justineo/vue-echarts#27]
![12](https://cloud.githubusercontent.com/assets/4061058/22183501/da99451e-e0fa-11e6-9c64-a6a4ecf70381.png)
![10](https://cloud.githubusercontent.com/assets/4061058/22183502/e03f2a92-e0fa-11e6-8a3e-44065fd1e859.png)
![11](https://cloud.githubusercontent.com/assets/4061058/22183505/e5cbb0b6-e0fa-11e6-859a-1978f29d1aa6.png)

如上图，当不选择时，y轴能不显示0-1的刻度吗。

**Comment by Justineo** [comment]
给 `yAxis` 配置 `axisLabel: {show: false}`，数据加载完设回 `true` 就行了，demo 已更新，可以自行查看代码。

**Comment by torresyb** [comment]
谢谢。。ok了。
