### ISSUE TITLE
如何引入主题

### ISSUE THREAD

**Issue by jairzh** [Justineo/vue-echarts#3]
尝试了好几种方式，都没有成功，可以给一个例子不？

**Comment by Justineo** [comment]
在 demo 中加入了引用自带主题和注册自定义主题的例子。

**Comment by jairzh** [comment]
Thanks a lot，已经成功。

不过用这种方式 import 不行 
```js
import chart from 'vue-echarts'
``` 

改成 demo 中的就可以了
```js
import chart from 'vue-echarts/src/components/ECharts.vue'
```

**Comment by Justineo** [comment]
`dist` 版本的没有把主题之类的打包进去，如果去引用本地 `node_modules` 里 `echarts/theme` 来注册其实是往另一个 `echarts` 实例上注册了，所以在 `vue-echarts` 里的这个取不到的。默认 build 的版本不会把各种主题扩展都打进去，如果有定制需求就引 `src` 下的来搞吧。
