### ISSUE TITLE
:options 初始必须有值是吧

### ISSUE THREAD

**Issue by shangxinbo** [Justineo/vue-echarts#31]
因为我的options 会在异步之后才能确定，本来想把options设为空，然后再异步后mergeOptions,但是会报错

**Comment by Justineo** [comment]
似乎的确可以先给个默认的，我抽空加一下。

**Comment by Justineo** [comment]
`v2.3.0` 开始可以在第一次赋值 `options` 时初始化。

**Comment by shangxinbo** [comment]
第一次赋值时初始化是什么意思，可以开始把options设为空么

**Comment by shangxinbo** [comment]
这没有解决我的问题，我已更新2.3.0

**Comment by adminlte** [comment]
@shangxinbo 初始options设空你最后是怎么解决的？
