### ISSUE TITLE
2.3.0 版本报错Unexpected token export

### ISSUE THREAD

**Issue by shangxinbo** [Justineo/vue-echarts#32]
在util.js 第34行 export { warn }

**Comment by shangxinbo** [comment]
可能是我的babel版本不够

**Comment by Justineo** [comment]
你用的是 vue-cli 初始化的项目是吗？如果是的话尝试按这个改一下先：https://github.com/Justineo/vue-echarts#heads-up

**Comment by shangxinbo** [comment]
这样做能起到什么作用呢？

**Comment by Justineo** [comment]
试过了吗？是否有效呢？

因为直接引入 component 而不是打包后的版本，会依赖你本地项目对 ESNext 代码做转译。之前 vue-cli 初始化完的配置会把 `node_modules` 从 `babel-loader` 排除掉，会导致代码没转译。

**Comment by shangxinbo** [comment]
并没有试，我改了一下util.js的那句代码 exports.warn =warn 就好了

**Comment by Justineo** [comment]
你这样并没有解决问题，代码没有过 Babel，能跑是因为你的浏览器已经支持了除 `import`/`export` 之外的已用的 ESNext 特性。
