### ISSUE TITLE
缺少 Vue.use 注册方案

### ISSUE THREAD

**Issue by liyanlong** [Justineo/vue-echarts#35]
```es6
import Vue from 'vue'
import ECharts from 'vue-echarts'
Vue.use(Echarts)
```
可以参照其它插件，给`vue-echarts`  加入注册钩子

**Comment by Justineo** [comment]
为什么不用 [`Vue.component`](https://vuejs.org/v2/api/#Vue-component)？

**Comment by liyanlong** [comment]
使用 `Vue.component` 是可行的的。
不过，我觉得应该采用这样的方式来使用会更加的简单

**Comment by Justineo** [comment]
这是 Vue 文档中推荐的组件注册方式。使用 `Vue.component` 或者注册本地组件可以让用户自行指定组件名称，避免冲突。
