### ISSUE TITLE
theme 该怎么用？

### ISSUE THREAD

**Issue by huteming** [Justineo/vue-echarts#36]
这是问题，并不是bug，只是我不知道该在哪里提问，很抱歉。
我想改变图表颜色，通过你的demo的做法，确实能改变主题色，但是我该怎么改自己想要的颜色呢？ECharts官方文档我也并没有找到theme字段。
很疑惑，求解答，谢谢

**Comment by Justineo** [comment]
生成主题：http://echarts.baidu.com/theme-builder/
导出类似 demo 中[主题](https://github.com/Justineo/vue-echarts/blob/master/demo/theme.json)的数据以后 `registerTheme` 就可以了。

**Comment by huteming** [comment]
没想到主题在下载栏里。已解决，非常感谢。

**Comment by taishan802** [comment]
请问下载栏在哪里？

**Comment by Justineo** [comment]
@taishan802 http://echarts.baidu.com/download-theme.html

**Comment by taishan802** [comment]
> 非常感谢你能回应我``

**Comment by SwpuEsine** [comment]
> import theme from '@/components/echarts/theme/macarons.js'
这种可以用吗,楼主,我发现这个无法生效啊
