### ISSUE TITLE
.echarts 无法使用media自适应，取消就可以了

### ISSUE THREAD

**Issue by jjjachyty** [Justineo/vue-echarts#37]
使用echarts3的时候 在移动端使用media自适应，无法动态改变大小（使用了auto-resize），发现是插件有样式
.echarts {
    width: 600px;
    height: 400px;
}
去掉width后就可以自适应了，请问如何使用media自适应？

**Comment by jjjachyty** [comment]
自定义样式
.echarts {
width: 100%;
height: 400px; --高度貌似无法改变
}

**Comment by Justineo** [comment]
`auto-resize` 目前只保证窗口大小变化后重新渲染图表。media query 自适应没问题的，demo 里面就是这么做的。600 宽和 400 高只是一个默认样式，你可以按你自己的需要去改成可以伸缩的尺寸。

**Comment by iceuncle** [comment]
没有明白什么意思呢？ 要怎样才能在移动端自适应呢？ 宽度一直都是600px，能麻烦详细说明一下吗？

**Comment by Justineo** [comment]
@iceuncle 你在 CSS 里覆盖掉默认样式啊，宽度设为 `100%`。
