### ISSUE TITLE
环形图series[i]-pie.label.normal.position 的inside属性无效

### ISSUE THREAD

**Issue by jackwangwj** [Justineo/vue-echarts#4]
项目直接引用会有个小bug
import chart from 'vue-echarts'
echart官方已解决，插件的打包版本估计旧了
[https://github.com/ecomfe/echarts/issues/2949](url)

**Comment by Justineo** [comment]
你用的是 dist 版本的话，更新是会不太及时的。如果你本地用了 `vue-loader` 的话可以直接 `import chart from 'src/components/ECharts.vue'` 这样其实会用你自己 `node_modules` 里的 `echarts`。

**Comment by Justineo** [comment]
`vue-echarts@0.1.2` 更新了依赖的 ECharts 版本。2.0 版本即将发布。
