### ISSUE TITLE
chart  width 和 height 怎么设置？还有如何做到自适应,demo中没找到相关方法

### ISSUE THREAD

**Issue by mackeystar** [Justineo/vue-echarts#48]

**Comment by Justineo** [comment]
写 CSS 的 `width` 和 `height` 属性就可以了。自适应目前只在浏览器窗口缩放时触发，给实例添加 `auto-resize` 属性即可。

**Comment by mackeystar** [comment]
ok，已解决

**Comment by wzj913906565** [comment]
求教何如解决的

**Comment by ly525** [comment]
@wzj913906565 
`<chart :option="chartOption" style="width:100%;"></chart>`

**Comment by owengaozhen** [comment]
为何这样设置不能自适应阿？
 "echarts": "3.8.5",      
  "vue-echarts": "2.6.0",
```
              <chart :auto-resize="true" :options="content" :width="echartsStyle.width" :height="echartsStyle.height"/>
```

**Comment by Redatee** [comment]
> 为何这样设置不能自适应阿？
> "echarts": "3.8.5",
> "vue-echarts": "2.6.0",
> 
> ```
>               <chart :auto-resize="true" :options="content" :width="echartsStyle.width" :height="echartsStyle.height"/>
> ```

<chart :options="content" :width="echartsStyle.width" :height="echartsStyle.height" auto-resize/>
这样就可以了

**Comment by Redatee** [comment]
> 为何这样设置不能自适应阿？
> "echarts": "3.8.5",
> "vue-echarts": "2.6.0",
> 
> ```
>               <chart :auto-resize="true" :options="content" :width="echartsStyle.width" :height="echartsStyle.height"/>
> ```




>   `<chart :options="content" :width="echartsStyle.width" :height="echartsStyle.height" auto-resize/>`

这样就可以了
