### ISSUE TITLE
你就不能像ECharts官方那样写个中文教程

### ISSUE THREAD

**Issue by zq99299** [Justineo/vue-echarts#49]
你就不能像ECharts官方那样写个中文教程，对于新手来说，完全不知道你这个东西怎么用哇。

**Comment by zq99299** [comment]
而且用不了。
import ECharts from 'vue-echarts/components/ECharts.vue';
Vue.component('chart', ECharts);
之后。整个项目都不能访问了

**Comment by Justineo** [comment]
如果看不懂英文的，你可以直接用百度翻译的[结果](http://fanyi.baidu.com/transpage?query=https%3A%2F%2Fgithub.com%2FJustineo%2Fvue-echarts&source=url&ie=utf8&from=auto&to=zh&render=1)对照着原始代码看一下嘛。不要期望别人帮你把什么都准备好。

说用不了，却又不提供任何错误信息，你指望别人给你提供什么样的帮助呢？看完 README，还有问题的先翻翻以前的 issue，实在解决不了再发 issue 求助，这是最基本的套路。

**Comment by zq99299** [comment]
import ECharts from 'vue-echarts/components/ECharts.vue';
Vue.component('chart', ECharts);

就这两句话。就出现下面的错误了。访问项目就抱个错
"vue-echarts":"^2.3.3"

util.js?df81:34 Uncaught SyntaxError: Unexpected token export
Uncaught SyntaxError: Unexpected token export  
    at Object.<anonymous> (app.js:2282)
    at __webpack_require__ (app.js:583)
    at fn (app.js:107)
    at eval (eval at <anonymous> (app.js:1655), <anonymous>:15:13)
    at Object.<anonymous> (app.js:1655)
    at __webpack_require__ (app.js:583)
    at fn (app.js:107)
    at eval (eval at <anonymous> (app.js:2327), <anonymous>:7:3)
    at Object.<anonymous> (app.js:2327)
    at __webpack_require__ (app.js:583)

**Comment by zq99299** [comment]
Uncaught SyntaxError: Unexpected token export
    at Object.<anonymous> (app.js:2282)
    at __webpack_require__ (app.js:583)
    at fn (app.js:107)
    at eval (eval at <anonymous> (app.js:1655), <anonymous>:15:13)
    at Object.<anonymous> (app.js:1655)
    at __webpack_require__ (app.js:583)
    at fn (app.js:107)
    at eval (eval at <anonymous> (app.js:2327), <anonymous>:7:3)
    at Object.<anonymous> (app.js:2327)
    at __webpack_require__ (app.js:583)
(anonymous)	@	app.js:2282
__webpack_require__	@	app.js:583
fn	@	app.js:107
(anonymous)	@	ECharts.vue?f0fa:17
(anonymous)	@	app.js:1655
__webpack_require__	@	app.js:583
fn	@	app.js:107
(anonymous)	@	ECharts.vue?6d48:7
(anonymous)	@	app.js:2327
__webpack_require__	@	app.js:583
fn	@	app.js:107
(anonymous)	@	main.js?3479:14
(anonymous)	@	app.js:1649
__webpack_require__	@	app.js:583
fn	@	app.js:107
(anonymous)	@	app.js:637
__webpack_require__	@	app.js:583
(anonymous)	@	app.js:629
(anonymous)	@	app.js:632

**Comment by zq99299** [comment]
主要是这个一引入进来就报错。才感觉怎么那么难用。还没开始就已经结束了。说话才有点冲。

**Comment by Justineo** [comment]
参考[这个](https://github.com/Justineo/vue-echarts#heads-up)改一下先？

**Comment by zq99299** [comment]
import VueECharts from 'vue-echarts';
Vue.component('chart', VueECharts);

这样就可以了。 导的js

**Comment by Justineo** [comment]
你这样导入会把整个 ECharts 一起打包进去，跑是可以跑的，但是有点大。

**Comment by zq99299** [comment]
哦。 明白了。

**Comment by zq99299** [comment]
//import VueECharts from 'vue-echarts';
 import VueECharts from 'vue-echarts/components/ECharts.vue';
 import 'echarts/lib/chart/pie';
Vue.component('chart', VueECharts);

这样导入 可以了。 但是 发现少了 能操作的东西。就是饼图左上角 有一个列表。点以下就隐藏一类数据那个操作列表 没有了。  直接引全部的。就有。 不知道怎么回事

**Comment by Justineo** [comment]
是这样的，如果要缩小打包体积，就要自己去找用到了哪些 ECharts 的功能，自己来导入。搞不清的话，直接导入 `vue-echarts` 也没问题。

**Comment by zq99299** [comment]
哦哦哦。 好把 ，明白了

**Comment by zq99299** [comment]
感谢

**Comment by huangyanxiong01** [comment]
@Justineo 这个README的getting-start的确要改，看着看着就分不清楚全局引用还是按需引用了

**Comment by gus-gu** [comment]
这手伸得如此的理直气壮

**Comment by zq99299** [comment]
两年前的话题了，哥哥，你还这么赶兴趣，现在这个项目也提供中文说明了，教程也比两年前完善了

**Comment by gus-gu** [comment]
要是我儿子这么提问早就大嘴巴抽了

**Comment by Justineo** [comment]
@gus-gu 都宽容一些吧~不继续讨论这个话题了。
