### ISSUE TITLE
打包还是会报错

### ISSUE THREAD

**Issue by JuZiSang** [Justineo/vue-echarts#50]
使用的最新版的vue-cli，按照README配置的
```js
      {
        test: /\.js$/,
        loader: 'babel-loader',
        exclude: /node_modules(?![\\/]vue-echarts[\\/])/,
        include: [
          resolve('src'),
          resolve('test'),
          resolve('node_modules/vue-echarts'),
          resolve('node_modules/echarts')
        ]
      }
```

util报错
```
ERROR in static/js/5.bd94499254ffc50f0d2b.js from UglifyJs
Unexpected token: name (warn) [./~/.2.3.3@vue-echarts/util.js:3,0][static/js/5.bd94499254ffc50f0d2b.js:22816,4]
```

这样导入的
```
  import Echarts from 'vue-echarts/components/ECharts.vue'
  import 'echarts/lib/chart/bar'
  import 'echarts/lib/component/tooltip'
  import 'echarts/lib/loading/default'
  Vue.component("Echarts",Echarts);
```

**Comment by Justineo** [comment]
最新版的 `vue-cli` 生成的代码只需要改 `babel-loader` 的 `include` 应该就可以了：

```js
      {
        test: /\.js$/,
        loader: 'babel-loader',
        include: [resolve('src'), resolve('test'), resolve('node_modules/vue-echarts')]
      },
```

**Comment by JuZiSang** [comment]
我重新新建了一个Vue项目，修改
```
      {
        test: /\.js$/,
        loader: 'babel-loader',
        include: [resolve('src'), resolve('test'), resolve('node_modules/vue-echarts')]
      }
```
还是会报这个错误，但是导入整个`vue-echarts`就没问题
```
ERROR in static/js/vendor.81be29fda88464a64051.js from UglifyJs
Unexpected token: name (warn) [./~/.2.3.3@vue-echarts/util.js:3,0][static/js/vendor.81be29fda88464a64051.js:30105,4]
```

**Comment by Justineo** [comment]
你是什么操作系统？`vue-cli` 版本是多少？我这里复现不了你的问题……

**Comment by JuZiSang** [comment]
win10，`vue-cli` 2.8.1 ，我试着更新下`vue-cli`试试

**Comment by JuZiSang** [comment]
发现把`import { warn } from '../util'`注释掉就没报错了，代码也正常压缩了
```js
import echarts from 'echarts/lib/echarts'
import debounce from 'lodash.debounce'
// import { warn } from '../util'

    _delegateMethod(name, ...args) {
      if (!this.chart) 
      return
      // warn{
      //   warn(`Cannot call [${name}] before the chart is initialized. Set prop [options] first.`, this)
      // }
      return this.chart[name](...args)
    },
```

**Comment by Justineo** [comment]
因为这个文件是 ES Next 的，而且不是用 vue-loader 加载的。你是 Windows 的话，再试一下把 `resolve('node_modules/vue-awesome')` 改成 `resolve('node_modules\\vue-awesome')` 试试呢？

**Comment by JuZiSang** [comment]
```js
            {
                test: /\.js$/,
                loader: 'babel-loader',
                include: [resolve('src'), resolve('test'), resolve('node_modules\\vue-awesome')]
            }
```
你是说这样？好像还是不行呢

**Comment by transtone** [comment]
mac下也报错。

**Comment by Justineo** [comment]
@transtone

能否给一下完整的初始化过程？最好有 `vue-cli` 版本和初始化时用的什么 template。

**Comment by soundtina** [comment]
@transtone  你重新pull 下代码, 重新npm install 应该就好了_

**Comment by yourcolour** [comment]
vue-cli版本:2.8.1,初始化模板命令:vue init webpack,系统:mac,vue-echarts版本:2.3.3.
构建的时候也是报这个压缩错误

**Comment by transtone** [comment]
需要这样来一下：
```js
      {
        test: /\.js$/,
        loader: 'babel-loader',
        include: [resolve('src'), resolve('test'), resolve('node_modules/vue-echarts')]
      },
```

**Comment by Justineo** [comment]
@JuZiSang @yourcolour 原来是我贴成了另一个项目的配置，你按 @transtone 说的来配置就可以了。

**Comment by Justineo** [comment]
@transtone 其实我上面[已经说了](https://github.com/Justineo/vue-echarts/issues/50#issuecomment-289369531)呀……

**Comment by yourcolour** [comment]
@JuZiSang @transtone 已解决,谢谢

**Comment by lhywell** [comment]
按 @transtone 的配置，启动报错 cannot to assign to read only property exports，提示lodash里面的isOjbect.js，module.exports报错，估计是babel编译问题，按照@JuZiSang配置可以，加上exclude: /node_modules(?![\\/]vue-echarts[\\/])/,

**Comment by TheJedinator** [comment]
I'm using vue and doing this in webpack: 
`     {
        exclude: path.resolve(__dirname, "node_modules"),
        test: /\.js$/,
        loaders: [{
          loader: 'babel-loader',
          query: {
            cacheDirectory: true,
          }
        }],
        include: [path.resolve('node_modules/vue-echarts')]
      },`

still not working for me. Any reccomendations? Get an error about vue-loader on ECharts.vue

**Comment by Justineo** [comment]
https://github.com/ecomfe/vue-echarts/issues/50#issuecomment-289369531

**Comment by TheJedinator** [comment]
@Justineo I have done that and still receiving the error.

**Comment by Justineo** [comment]
@TheJedinator Do you have a minimal reproduction?

**Comment by feijuncheng** [comment]
```
{
        test: /\.js$/,
        loader: 'babel-loader',
        include: [
          resolve('src'),
          resolve('test'),
          resolve('node_modules/vue-echarts'),
          resolve('node_modules/resize-detector')
        ]
      }
```

我用上面这个配置，在本地windows打包是好的，但是在jenkins上是不好的。4.0.1版本
