### ISSUE TITLE
npm install and error occurs

### ISSUE THREAD

**Issue by smalllong** [Justineo/vue-echarts#51]

**Comment by Justineo** [comment]
Can you elaborate this?

**Comment by smalllong** [comment]
79% [0] building modules 448/453 modules 5 active ...dules\zrender\lib\animatio
 79% [0] building modules 449/453 modules 4 active ...dules\zrender\lib\animatio
 79% [0] building modules 450/453 modules 3 active ...dules\zrender\lib\animatio
 79% [0] building modules 451/453 modules 2 active ...dules\zrender\lib\animatio
 79% [0] building modules 452/453 modules 1 active ...dules\zrender\lib\animatio
[0] Hash: cdda89c65e8d56ddffdc1eac74fb9e94e12beb9a
Version: webpack 2.1.0-beta.22
Child
    Hash: cdda89c65e8d56ddffdc
    Version: webpack 2.1.0-beta.22
    Time: 18578ms
        Asset    Size  Chunks             Chunk Names
    bundle.js  775 kB       0  [emitted]  main
Child
    Hash: 1eac74fb9e94e12beb9a
    Version: webpack 2.1.0-beta.22
    Time: 18410ms
             Asset    Size  Chunks             Chunk Names
    vue-echarts.js  632 kB       0  [emitted]  main
'cp' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\ch
okidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@
1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"}
)
npm WARN vue-echarts@2.3.3 No repository field.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vue-echarts@2.3.3 prepublish: `npm run build && cp -r ./src/* .`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vue-echarts@2.3.3 prepublish script 'npm run build && cp
-r ./src/* .'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the vue-echarts package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build && cp -r ./src/* .
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs vue-echarts
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls vue-echarts
npm ERR! There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\XL\AppData\Roaming\npm-cache\_logs\2017-03-27T07_05_22_945
Z-debug.log

**Comment by Justineo** [comment]
好吧，Windows 下跑 npm script 失败了，我找时间修复一下吧……

**Comment by soundtina** [comment]
我有个疑问，为什么`prepublish` 的时候要把这些文件拷贝的根目录？

**Comment by Justineo** [comment]
@soundtina 在直接引入 `.vue` 文件时路径可以短一些。

**Comment by soundtina** [comment]
![image](https://cloud.githubusercontent.com/assets/4946901/24409139/e9a5825e-1401-11e7-9570-6d5654942e8d.png)
我看到webpack打包的入口，还是用的src里面的，这个地方是应该改一下吗？

**Comment by TingYinHelen** [comment]
为什么我mac安装也失败了呢

**Comment by Justineo** [comment]
@TingYinHelen 错误信息？

**Comment by Justineo** [comment]
@TingYinHelen Nevermind. 看到新 issue 了。

**Comment by Justineo** [comment]
@smalllong Hi, the latest version should solve this problem. Welcome to try and reopen this issue if the problem still exists.
