### ISSUE TITLE
按需引入出错

### ISSUE THREAD

**Issue by arzcl** [Justineo/vue-echarts#53]
环境：
win10 vue-cli：2.8.1 vue : 2.2.6
在main.js里面引入
```
import` ECharts from 'vue-echarts/components/ECharts.vue'
import 'echarts/lib/chart/line'
import 'echarts/lib/component/tooltip'
```

在.vue文件使用：
<echart :options="polar"></echart>

报错
```
[Vue warn]: Error in mounted hook: 
TypeError: Cannot read property 'findAxisModel' of undefined
```

**Comment by Justineo** [comment]
`findAxisModel` 在你引入的两个模块中么？

**Comment by arzcl** [comment]
@Justineo 我就复制README.md里面的例子运行，就有这个错误，应该不在吧，我在Echart官网找不到findAxisModel

**Comment by Justineo** [comment]
如果要按需加载的，需要自己找到对应的功能在哪个模块里面。README 里面的例子显然不是你调用啥功能都有效的啊。

**Comment by arzcl** [comment]
@Justineo 非常抱歉，昨天有把全部模块都一一加载进去了，也是提示这个问题，今天回来上班发现可以了......................感谢您的解答

**Comment by xroom** [comment]
我也碰到这个问题。 首页的例子跑不起来

**Comment by Justineo** [comment]
@xroom README 的代码只是展示用的，具体的请看项目 demo 目录下的例子。

**Comment by Robin-zero** [comment]
@Justineo demo 目录下面是压缩之后的，如何看未压缩的源代码呢？

**Comment by Justineo** [comment]
@Robin-zero `src/demo`
