### ISSUE TITLE
跟着demo换theme失败，仍然是默认的主题，但是没有报任何错误

### ISSUE THREAD

**Issue by DanielWLam** [Justineo/vue-echarts#54]
webpack2做的构建工具，webpack2默认可以打包json文件，theme是demo中的theme，但是构建出来仍然是默认的主题，不知道是不是跟webpack2有关？

**Comment by Justineo** [comment]
注册主题的代码是怎么写的呢？

**Comment by DanielWLam** [comment]
``` js

import Vue from 'vue'
import ECharts from 'vue-echarts/components/ECharts.vue'
...
ECharts.registerTheme('test', theme)
...
Vue.component('chart', ECharts)
...

```

**Comment by Justineo** [comment]
`theme` 是哪里的？

**Comment by DanielWLam** [comment]
```js
import theme from './assets/theme.json'
```
漏了，抱歉，资源引用应该是没问题的，要不然编译就不通过，JSON文件就是demo中的json内容

**Comment by DanielWLam** [comment]
那啥，我看了一下代码，theme作为prop，一开始没有传入值，registerTheme只是注册了这个theme，但是没有使用

**Comment by Justineo** [comment]
`registerTheme` 只是为了让 `echarts` 实例能够记录这个主题，以便在初始化时识别。`theme` 需要从外部组件传入啊，你是像 [demo 里这么使用](https://github.com/Justineo/vue-echarts/blob/fd392b086c0b7d13b37c8a1d29c2bc43cac1c9a3/demo/Demo.vue#L8)的吗？

**Comment by DanielWLam** [comment]
还真没看到theme这个prop。。但如果这样的话，每个chart组件都要写一遍主题，我选择的是直接在EChart组件指定注册的theme

**Comment by Justineo** [comment]
ECharts 似乎没有提供这样的接口吧，你可以给 ECharts 发 feature request，让他们提供全局配置主题的功能。
