### ISSUE TITLE
npm run build 失败

### ISSUE THREAD

**Issue by qianlifeng** [Justineo/vue-echarts#57]
你好，今天使用了vue-echarts，效果不错。但是在编译的时候发生了错误。我也翻阅了前面已经closed的一些issue，但是好像没有效果。

重现步骤：
1. `vue init webpack my-project`
2. `npm install vue-echarts --save`
3. `vim my-project/src/main.js` 增加 vue-echart引用  

```javascript
// The Vue build version to load with the `import` command
// (runtime-only or standalone) has been set in webpack.base.conf with an alias.
import Vue from 'vue'
import App from './App'
import ECharts from 'vue-echarts/components/ECharts.vue'

Vue.config.productionTip = false

/* eslint-disable no-new */
new Vue({
  el: '#app',
  template: '<App/>',
  components: { App }
})
```
4. **`vim build/webpack.base.conf.js` 对babel-loader include vue-echarts**
```
 {
        test: /\.js$/,
        loader: 'babel-loader',
        query: {
            presets: ['env']
        },
        include: [resolve('src'), resolve('test'), resolve('node_modules/vue-echarts')]
}
```
5. `npm run build` 编译项目

然后出现如下错误：
```
Unexpected token: name (warn) [./~/.2.3.3@vue-echarts/util.js:3,0][static/js/vendor.ee15db300e132565ba51.js:22452,4]
```

看错误应该是vue-echarts用了ES6的写法，难道babel-loader没有把相关的代码转过来？

**Comment by Justineo** [comment]
参考一下 https://github.com/Justineo/vue-echarts/issues/50#issuecomment-289369531

**Comment by Justineo** [comment]
你的操作系统是？

**Comment by qianlifeng** [comment]
OS X EI Capitan

**Comment by dwk715** [comment]
@qianlifeng 请问解决了吗？
我也在build时遇到了相似的问题

**Comment by Justineo** [comment]
我本地无法重现这个问题，是打包时就失败了？@qianlifeng 我按你说的步骤进行打包，结果是：

![image](https://cloud.githubusercontent.com/assets/1726061/24947813/bf745862-1f9a-11e7-8f44-35b92e62922a.png)

**Comment by qianlifeng** [comment]
是的，我刚刚又走了一边，不行的。run build的时候就失败了。

![wx20170412-181737](https://cloud.githubusercontent.com/assets/1725475/24953025/5a5ca012-1fac-11e7-84d5-8fb05dcba21a.png)

**Comment by wushan** [comment]
<img width="928" alt="screenshot 2017-04-13 18 59 05" src="https://cloud.githubusercontent.com/assets/3633628/25002120/5c01b95a-207b-11e7-8cdb-c92990faf148.png">

Same issue here.

**Comment by strebl** [comment]
Did you all change your wepback config? https://github.com/Justineo/vue-echarts#heads-up

That fixed that error for me.

**Comment by qianlifeng** [comment]
@strebl  Yes, I have changed my webpack config , see the point 4.

**Comment by Justineo** [comment]
Webpack config no longer need to be modified since `v2.3.4` because warnings are utilizing `Vue.util.warn` now.
