### ISSUE TITLE
let warn = () => {} syntax error with IE

### ISSUE THREAD

**Issue by hpsoar** [Justineo/vue-echarts#58]
when i open my site with IE, it gives me this error.

is vue-echarts ie compatible?

or how should i fix this?

BR.

**Comment by Justineo** [comment]
Have you tried [this](https://github.com/Justineo/vue-echarts#heads-up) stated in the readme yet?

**Comment by hpsoar** [comment]
Yes, thank you it works!

**Comment by MichalKrakow** [comment]
How to make [this](https://github.com/ecomfe/vue-echarts#%EF%B8%8F-heads-up) work with laravel mix?
