### ISSUE TITLE
注册地图数据 失败 fail to register the Map data

### ISSUE THREAD

**Issue by josephvong** [Justineo/vue-echarts#60]
我的代码：
Vue 项目下 的 main.js中：
加载了以下 模块： 
import chinaMap from './china.json' //加载map数据
import VueECharts from 'vue-echarts/components/ECharts.vue'
import 'echarts/lib/chart/map' // 加载 map 组件
import 'echarts/lib/chart/scatter' // 加载 scatter 组件
import 'echarts/lib/chart/effectScatter' // 加载 effecterScatter 组件
// console.log( chinaMap ) 测试输出 chinaMap 正常

注册 地图 和全局 组件
VueECharts.registerMap('china', chinaMap) // 注册map 数据
Vue.component('chart', VueECharts) // 注册 chart组件

App.vue 组件里面：
import mapData from './mapData'  // 引入图标数据（用demo的数据）
Vue 组件里： 定义 data 
  name: 'app',
  data(){
    return {
      mapData:mapData
    }
  },
可以输出 this.mapData ,  证明 mapData 调用正常

但是 地图效果并无输出，打开控制台查看节点， 对应位置 没有 canvas 生成， 请问是什么问题？

另外 打开 china.JSON，发现为乱码 如下：
{"type":"FeatureCollection","features":[{"id":"710000","geometry":{"type":"MultiPolygon","coordinates":[["@@°Ü¯Û","@@ƛĴÕƊÉɼģºðʀ\\ƎsÆNŌÔĚänÜƤɊĂǀĆĴĤǊŨxĚĮǂƺòƌâÔ®ĮXŦţƸZûÐƕƑGđ¨ĭMó·ęcëƝɉlÝƯֹÅŃ^Ó·śŃǋƏďíåɛGɉ¿IċããF¥ĘWǬÏĶñÄ","@@\\p|WoYG¿¥Ij@","@@¡@V^RqBbAnTXeQr©C","@@ÆEEkWqë I"]],"encodeOffsets":[[[122886,24033],[123335,22980],[122375,24193],[122518,24117],[124427,22618]]]},"properties":{"cp":[121.509062,25.044332],"name":"台湾","childNum":5}},{"id":"130000","geometry":{"type":"MultiPolygon","coordinates":[["@@\\aM`Ç½ÓnUKĜēs¤­©yrý§uģcJ»eIP]ªrºc_ħ²G¼s`jÎŸnüsÂľP","@@U`Ts¿mÄ","@@FOhđ©OiÃ`ww^ÌkÑH«ƇǤŗĺtFu{Z}Ö@U´ʚLg®¯Oı°Ãw ^VbÉsmAê]]w§RRl£ŭuwNÁ`ÇFēÝčȻuT¡Ĺ¯Õ¯sŗő£YªhVƍ£ƅnëYNgq¼ś¿µı²UºÝUąąŖóxV@tƯJ]eR¾fe|rHA|h~Ėƍl§ÏjVë` ØoÅbbx³^zÃĶ¶Sj®AyÂhðk`«PËµEFÛ¬Y¨Ļrõqi¼Wi°§Ð±²°`[À|ĠO@ÆxO\\ta\\p_Zõ^û{ġȧXýĪÓjùÎRb^Î»j{íděYfíÙTymńŵōHim½éŅ­aVcř§ax¹XŻácWU£ôãºQ¨÷Ñws¥qEHÙ|šYQoŕÇyáĂ£MÃ

**Comment by josephvong** [comment]
@Justineo 你好，请问 地图注册这里 有什么问题没有？ 我是跟着你的demo 来做的。echarts的组建我也按需加入了，就是 地图 没办法显示出来，控制台没有报错，而且，另一个chart 显示是正常的，我用相同的方式 写了个bar 的chart 试验过了。

**Comment by Justineo** [comment]
如果你能跑得起来 demo，并且看到里面的地图，那就可能不是 Vue-Echarts 的问题了。

**Comment by josephvong** [comment]
@Justineo 
我也是按的是demo 的方式来的：
index.js  里面
import ECharts from 'vue-echarts/components/ECharts.vue'
Vue.component('chart', ECharts) // 注册 chart组件
App.vue 里面：
import ECharts from 'vue-echarts/components/ECharts.vue'
import 'echarts/lib/chart/map' // 加载 map 组件 （你的demo里面没有这个，不过我这边不加的话会报错）
import map from './map'
import chinaMap from './china.json' //加载map数据 （用你项目的数据）
import chinaMap from 'echarts/map/json/china.json' //加载map数据（用node_module里面的数据）
export default{
    ......
   components:{ 
         'chart':ECharts  // 在 App.vue 里面再 注册chart 组建，你demo里面没有这个，不过我不加会报错。
    },
}

**Comment by josephvong** [comment]
问题解决了，被 readme 哪里的 指引坑了；
@Justineo  你 首页哪里 npm 的使用方式是 import ECharts from 'vue-echarts/components/ECharts.vue'
然而 这个方法却无法 出现效果；
然后，我用 import ECharts from 'vue-echarts‘ 就可以了

**Comment by Justineo** [comment]
```js
import ECharts from 'vue-echarts'
```

这样会把整个 ECharts 都加载进去而只加载 `.vue` 文件不会。

**Comment by josephvong** [comment]
但是 我试过 import ECharts from 'vue-echarts/components/ECharts.vue' 的方法 不行啊！没办法生成canvas，那是什么问题呢，PS 我 是cnpm 下载的，不知道有没有关系？

**Comment by cike8899** [comment]
我遇到了同样的问题，`import ECharts from 'vue-echarts/components/ECharts.vue'`这么引入的话，ECharts.vue _init() 拿不到echarts这个变量`let chart = echarts.init(this.$el, this.theme, this.initOptions)`拿不到

**Comment by Justineo** [comment]
@cike8899 为什么要拿 `echarts` 这个变量？

**Comment by cike8899** [comment]
`import ECharts from 'vue-echarts/components/ECharts.vue'` 是你的代码里面 _init函数用到的

**Comment by Justineo** [comment]
@cike8899 能完整组织一下问题吗？`echarts` 找不到的话是报错了？

**Comment by cike8899** [comment]
我在main.js  import ECharts from 'vue-echarts/components/ECharts.vue'这么引入的话，ECharts.vue _init() 拿不到echarts这个变量let chart = echarts.init(this.$el, this.theme, this.initOptions)拿不到,断点进了Charts.vue文件发现_init()函数中的let chart = echarts.init(this.$el, this.theme, this.initOptions)这句话的echarts变量是undefined，然后import ECharts from 'vue-echarts'这么做的话就没问题了。

**Comment by Justineo** [comment]
@cike8899 看一下最新版是否仍有问题？如果还有的话开新 issue 吧，不是这个 issue 相关的问题了。
