### ISSUE TITLE
webpack 打包出错，可否发布一个 babel 处理过的打包版本？

### ISSUE THREAD

**Issue by transtone** [Justineo/vue-echarts#61]
是否可以不用 warn 这个组件？或者换一个相同功能的插件呢？
因为需要在nuxt中使用 vue-echarts，而nuxt的webpack配置是隐藏了的不能修改的，造成这个问题绕不过去。

而且刚看了 vue 源码，debug.js 的内容已有调整。另外可否联系尤大咨询一下这个问题呢，毕竟 vue 本身没有出现这个 uglify-js 不认的情况。

仔细想了一下，这应该是按需加载引用方式的问题。有没有别的好方法处理按需加载？

强行调用 babel 去处理 node_modules 里的组件，毕竟不是个好的方法。

**Comment by Justineo** [comment]
我下一个版本把它去掉吧。

**Comment by Justineo** [comment]
`v2.3.4` 已经改为直接调用 `Vue.util.warn`，不再需要修改 Webpack 配置了。
