### ISSUE TITLE
引入 EChart 报错

### ISSUE THREAD

**Issue by josephvong** [Justineo/vue-echarts#65]
代码如下： 
import ECharts from 'vue-echarts'   // 之前尝试 用 vue-echarts/component/.... 方式引用 也失败
import map from 'common/data/map'
import chinaMap from 'common/data/china.json' //加载map数据
ECharts.registerMap('china', chinaMap) // 注册中国地图**

报错如下：
vue-echarts.js?4139:19 
Uncaught TypeError: Cannot assign to read only property 'exports' of object '#<Object>'

**Comment by Justineo** [comment]
最新版如果仍有问题请 reopen。

**Comment by xcchcaptain** [comment]
vue cli3 的情况下，仍然出现这个问题
