### ISSUE TITLE
uncaught ReferenceError: __DEV__ is not defined

### ISSUE THREAD

**Issue by herman7** [Justineo/vue-echarts#68]
兄弟，弄一晚上了，按照你的文档里面配置的，
我用的ES Modules with NPM & vue-loader方式配置的，就是直接在main.js里面引入：
```
import ECharts from 'vue-echarts';
import 'echarts/lib/chart/bar';
import 'echarts/lib/chart/line';
import 'echarts/lib/chart/lines';
import 'echarts/lib/component/tooltip';

  Vue.component('chart', ECharts);
```

报这个错误，
原来用的旧版本是好用的，但是升级后就出问题了，我现在的版本是
vue-echarts@2.3.7
echarts@3.5.3 
vue 2.0+

如果能提供一些帮助或建议，非常感谢您。

**Comment by Justineo** [comment]
```js
// only import modules you need
// 按需加载
import ECharts from 'vue-echarts/components/ECharts.vue';
import 'echarts/lib/chart/bar';
import 'echarts/lib/chart/line';
import 'echarts/lib/chart/lines';
import 'echarts/lib/component/tooltip';

Vue.component('chart', ECharts);
```

或者

```js
// import the default bundled version of ECharts
// 加载 ECharts 默认的完整包
import ECharts from 'vue-echarts';

Vue.component('chart', ECharts);
```

**Comment by Justineo** [comment]
如仍有问题欢迎 reopen。

**Comment by zema1** [comment]
我也遇到这个问题了.. 用全局的Vue.component 来注册会出错， 放到单个view中注册就没问题，我也不知道这是谁的锅。。

**Comment by Justineo** [comment]
@zema1 怎么配置的

**Comment by xjccc** [comment]
亲，请问，echarts里面有一个柱状图，形状是饼图的样子，那个应该引入什么，我引入polar之后还要引入什么呢？现在也是报这个错误。http://echarts.baidu.com/demo.html#bar-polar-stack就是这个地址的图

**Comment by Justineo** [comment]
@xjccc 你用的是哪个版本的 ECharts？最新版本的 ECharts 有 breaking change。还没有解决。

**Comment by xjccc** [comment]
"vue": "^2.5.2",
 "vue-echarts": "^2.5.0"
这个是最新的吗

**Comment by Justineo** [comment]
https://github.com/ecomfe/echarts/issues/6984

**Comment by xjccc** [comment]
@Justineo 抱歉，新手。是说我要安装指定版本的echarts吗？然后需要用echarts来实现吗

**Comment by Justineo** [comment]
你需要直接在本地 `npm install` 这两个库的老版本。看上面那个 issue 里面有人贴了可用的版本。

**Comment by xjccc** [comment]
好的，谢谢 @Justineo

**Comment by xjccc** [comment]
@Justineo   
in ./node_modules/vue-echarts/components/ECharts.vue

218:4-11 "export 'default' (imported as 'echarts') was not found in 'echarts/lib/echarts'
这个是什么原因呢- -

**Comment by xjccc** [comment]
我npm i echarts@3.6.2 zrender@3.5.2 --save   这两个- -。然后还是报Uncaught ReferenceError: __DEV__ is not defined
