### ISSUE TITLE
请问如何调用resize方法？

### ISSUE THREAD

**Issue by HuanMeng0** [Justineo/vue-echarts#7]
请问如何调用resize方法？
我使用的是NPM上的最新版本。
先谢谢了。

**Comment by Justineo** [comment]
更新了一下 [demo](https://github.com/Justineo/vue-echarts/blob/b42d516637e78129260ce78762731f48b3109a44/demo/Demo.vue#L131-L134) 。

**Comment by HuanMeng0** [comment]
谢谢
