### ISSUE TITLE
Error: Component series.line not exists. Load it first.

### ISSUE THREAD

**Issue by hank2718** [Justineo/vue-echarts#72]
用的https://github.com/Justineo/vue-echarts#using-the-component这个数据  出现的错误![image](https://cloud.githubusercontent.com/assets/7368299/25657477/9b3d37ce-3030-11e7-87f1-15f93ed05d83.png)

**Comment by Justineo** [comment]
如果你引入的是 `vue-echarts/components/ECharts.vue`，那么你需要自行引入实际用到的 `echarts` 模块。

可以参考一下 [ECharts 官方文档](http://echarts.baidu.com/tutorial.html) &rarr; 在 webpack 中使用 ECharts &rarr; 按需引入 ECharts 图表和组件

`vue-echarts/components/ECharts.vue` 已经引入了 `echarts/lib/echarts`，你需要按需引入其他部分。

**Comment by hank2718** [comment]
![image](https://cloud.githubusercontent.com/assets/7368299/25687735/82407684-30ab-11e7-9cbf-64b4dcc7c55c.png)
已经引入了所需的模块啊

**Comment by Justineo** [comment]
显然没有引入 line 啊……

**Comment by hank2718** [comment]
谢谢 解决了  其实我都引入了  重启了一下webstorm就好了   可能是ide的问题

**Comment by tangrianand** [comment]
I am facing the same issue. Can you please explain the solution if any in english?

**Comment by Justineo** [comment]
@tangrianand 

```js
import 'echarts/lib/chart/line'
```

See https://github.com/ecomfe/vue-echarts#es-modules-with-npm--vue-loader-recommended.
