### ISSUE TITLE
如何调用echarts自带的方法

### ISSUE THREAD

**Issue by Anluis** [Justineo/vue-echarts#73]
如同这个示例 http://echarts.baidu.com/demo.html#calendar-pie
里面的echarts.util.map(scatterData, function (item, index) 

谢谢！

**Comment by Justineo** [comment]
`util` 不在 ECharts 对外公开的 API 之列。而且你说的这个，根本不需要用 ECharts 来实现，在支持 ES5 的环境下直接 `scatterData.map(function (item, index) { ... })` 就可以了。
