### ISSUE TITLE
Trying to view polar chart via cdn

### ISSUE THREAD

**Issue by stangeorge** [Justineo/vue-echarts#74]
http://jsfiddle.net/2rpsyqp0/

I have the chart showing but I can't get the data to populate. I tried a few things and commented some code in that jsfiddle. Nothing helped. I am new to Vue and ECharts so I must be missing something basic.

Thanks

**Comment by Justineo** [comment]
I don't think it's the right place to ask here. You can first try to configure chart options on [ECharts gallery](http://gallery.echartsjs.com/editor.html) and once it works there but not working for Vue-Echarts, then it may be something wrong here.
