### ISSUE TITLE
No coordinate system that supports convertToPixel found by the given finder

### ISSUE THREAD

**Issue by Anluis** [Justineo/vue-echarts#75]
你好，我在使用convertToPixel(finder, value)方法的时候，设置finder 为 'calendar'，在控制台出现如上警告，图表无法渲染。
是否暂不可使用 calendar 坐标系?谢谢。

**Comment by Justineo** [comment]
你应该去 ECharts 本身的 issue 提这个问题吧？

**Comment by Anluis** [comment]
我看在Echarts 3.5版本才支持了日历坐标系，您的这个项目所用到的Echarts版本是否在这之上呢？如果没有是否有升级的计划？谢谢。

**Comment by Justineo** [comment]
预编译的版本是基于 ECharts 3.3.2 的，但是如果你不是直接引用打包好的版本，是不受这个影响的，你自己把项目中用到的 ECharts 升级到最新的就可以了。

**Comment by Anluis** [comment]
项目中的ECharts是3.5.2的，所以这个问题应该去ECharts本身的 issue提，谢谢。

**Comment by Justineo** [comment]
@Anluis 前提是你引入的是 `vue-echarts/components/ECharts.vue`。

**Comment by Anluis** [comment]
如果我
import ECharts from 'vue-echarts/components/ECharts.vue';
 ，则会报错

This relative module was not found:

* ../util in ./~/babel-loader?cacheDirectory!./~/vue-loader/lib/selector.js?type=script&index=0!./~/vue-echarts/components/ECharts.vue 

使用的是Laravel-mix，依赖的webpack版本是2.2.1，请问可能是哪方面的错误？

**Comment by Justineo** [comment]
你用的是最新版本的 vue-echarts 么?

**Comment by Anluis** [comment]
之前不是，更新到最新版本后引入.vue文件：
import ECharts from 'vue-echarts/components/ECharts.vue';
可以，但是在使用时依然报错：
found in <Chart> at /Applications/XAMPP/xamppfiles/htdocs/**/node_modules/vue-echarts/components/ECharts.vue
Error: Component series.pie not exists. Load it first.

使用的是Vue.component('chart', ECharts);
在入口js注册，
之前使用
import VueECharts from 'vue-echarts'; 
则没有问题

**Comment by Anluis** [comment]
日历图可以使用了，用的是
import VueECharts from 'vue-echarts'; 
这种方式引用，是 @Justineo 更新了预编译的文件？
以后正确的引用方式就是这样引用了吗？谢谢🙏

**Comment by Justineo** [comment]
> Error: Component series.pie not exists. Load it first.

你需要自行引入 ECharts 的子模块，以减小打包体积。请看 README。

> 这种方式引用，是 @Justineo 更新了预编译的文件？

没有更新过预编译的文件，你是否重复引入了 ECharts？

**Comment by Anluis** [comment]
明白了，已经解决，感谢 Justineo

**Comment by ColinCLL** [comment]
请问是通过 import VueECharts from 'vue-echarts';引入vue-echarts模块，再通过vue.use(echarts)引入新的版本echart吗？

**Comment by Justineo** [comment]
@ColinCLL 看 README 啊哥哥……
