### ISSUE TITLE
结合element UI的tabs使用问题和map的问题

### ISSUE THREAD

**Issue by ColinCLL** [Justineo/vue-echarts#76]
遇到问题：
1.在使用Element UI的tab中，我把原有的.echarts样式宽高覆盖掉成百分比，除了tab的第一页的图表正常，其他页均变成固定宽高100px; 
2.地图中官网例子：http://echarts.baidu.com/demo.html#map-china-dataRange   搬过来无法显示具体地址中上面那些小点，但在本地使用静态html下载对应版本echart使用发现没问题。我本地使用的版本下载链接https://cdn.bootcss.com/echarts/3.3.2/echarts.common.min.js
期望结果：
1问题中解决问题，在Element UI 的tabs组件中可以使用宽高百分比布局。或者帮我找到对应问题的代码位置，我试着去改。
2问题能正常显示地图上方具体地址上方的小点。

![e1](https://cloud.githubusercontent.com/assets/19434659/25980797/9dc1210c-3703-11e7-9b49-25853e0df40d.jpg)
![echart](https://cloud.githubusercontent.com/assets/19434659/25980820/c173d842-3703-11e7-8cd2-e0cd916cc695.jpg)

**Comment by Justineo** [comment]
ECharts 必须在容器大小确定后重新渲染才能正常显示。你可以在 Tab 切换以后调用图表组件的 `resize()` 方法来实现。

**Comment by ColinCLL** [comment]
谢谢你的及时回复，我试了很久，第一个问题应该ElementUI的问题，除了当前页面的tab，其他页面的所有的宽度都是0。我想这个问题我应该去ElementUI那边去问问，tab之后dom完成宽高改变之后的回调函数是什么，点击tab直接调用resize渲染dom还是宽高0。

**Comment by ColinCLL** [comment]
关于第一个问题我已经解决。第二个问题的话，请问可以支持自定义更新或者使用echarts的版本吗？

**Comment by Justineo** [comment]
可以先参考一下这个：https://github.com/Justineo/vue-echarts/issues/75#issuecomment-300743830

**Comment by Cedric-song** [comment]
@ColinCLL 其实我也同时在用elementUI和vue-echarts，在使用tab的时候确实会出现此问题。tab的切换其实就是diaplay设为none，如果element用z-index来处理就好了。或者vue-echarts提供一个后加载的props也是可以的。

我使用的两种方式：
1. 把echarts的初始options设为空字符串，在tab切换的时候给它赋值，这样的问题就是vue-charts会给我一个告警，说options定义了props的类型为Object。
2. 在切换的时候，手动计算一下map的宽高，给宽高先赋值。

利弊：
方法1会产生告警，未来升级vue-echarts的时候要谨慎，有可能有出问题。
方法2很繁琐，要在每个有map的页面中做计算。

综合：
我目前使用的方法1，希望vue-echarts的作者可以在后续版本给一个延后初始化echarts的属性。

**Comment by ColinCLL** [comment]
@Cedric-song 你的建议很不错，不过我自己在这个问题上也通过别人的帮助找到了自己方法。其实是每次切换tabs的时候，tab都要重新渲染一次。使用this.$nextTick方法，这个方法会在vue完成渲染之后再调用。这时就可以使用resize()方法。

缺点就是切换之后会有一个从小到大出现图表的动画。不过这个目前对我来说还省了我写动画的功夫。

**Comment by Justineo** [comment]
> 希望vue-echarts的作者可以在后续版本给一个延后初始化echarts的属性

现在已经有了吧，只要上来 `options` 为 `null`，就不会初始化。第一次设置 `options` 属性的时候才会进行初始化。

用 `$nextTick` + `resize` 做处理我觉得也没什么毛病。

**Comment by Cedric-song** [comment]
哦哦，了解。试了，OK的。

**Comment by tingrun919** [comment]
@ColinCLL 我想请问一下第一个问题你是如何解决的，在ElementUI的tab中切换不同的tab，显示不同，或者相同的Echarts，只有第一个显示正常的解决方法。

**Comment by ColinCLL** [comment]
ele-UI的话在tab切换的回调函数handleClick里面使用this.$nextTick。

this.$nextTick里面调用图表的resize方法。

**Comment by tingrun919** [comment]
但是我的echarts是作为子组件引入的，这种情况下依然适用吗？

**Comment by ColinCLL** [comment]
这个js插件也有resize方法啊。
tmp：
<echarts :options="pieOption" ref="pie" auto-resize class="chart"></echarts>
js:
this.$refs.pie.resize();

**Comment by xiaopo1991** [comment]
也遇到了这个问题，解决了，看文档，里面有个auto-resize属性，不设置这个属性的话，默认是false，设成true就行了

**Comment by DorisOu** [comment]
@ColinCLL @xiaopo1991 能写下具体点的代码么？我也是使用element-ui （tab）和 echarts（作为组件），第一个tab的echartss图表显示正常，第二个tab的完全没有出现。。。。
