### ISSUE TITLE
缺少实例方法getOption

### ISSUE THREAD

**Issue by zhangya5847** [Justineo/vue-echarts#77]
现在有个业务，按钮控制柱状图的缩放，通过dispatchAction 可以实现，但是要设置startValue，并且希望这个值是在原来值的基础上计算得到的，这个值需要用getOption来获取。组件没有提供。
   期待您的回复！

**Comment by Justineo** [comment]
暂时可以通过用 ref 取得组件实例以后，通过 `chart` 属性得到内部的 ECharts 实例来解决。

**Comment by zhangya5847** [comment]
好的，谢谢回复！

**Comment by Justineo** [comment]
在 `vue-echarts@2.4.0` 增加了一个 `computedOptions` 属性，来获取 `getOption` 的结果。这个属性是 reactive 但是只读的。
