### ISSUE TITLE
请问能把 echarts的扩展库整合进去吗？

### ISSUE THREAD

**Issue by 188007803** [Justineo/vue-echarts#78]
比如：字符云 wordcloud，如果需要手动整合，该怎么做呢？ 谢谢！

**Comment by Justineo** [comment]
https://github.com/Justineo/vue-echarts/blob/master/demo/Demo.vue#L260

参考这个，一样的。

**Comment by 188007803** [comment]
好像已经不支持了。引入报错！！
 [Vue warn]: Error in callback for watcher "options": "Error: Component series.wordCloud not exists. Load it first."

**Comment by Justineo** [comment]
https://github.com/Justineo/vue-echarts#es-modules-with-npm--vue-loader-recommended

**Comment by Justineo** [comment]
先关闭了，有问题可以再开。

**Comment by 188007803** [comment]
感谢你，我找到一个基于wordcloud2的加强版，先就用这个吧，不用整合到echarts中了。

**Comment by Fengdongxing** [comment]
有全国的城市地图数据js吗？

**Comment by Fengdongxing** [comment]
还有demo.vue的qs是什么来的？
