### ISSUE TITLE
動態改變 theme

### ISSUE THREAD

**Issue by wushan** [Justineo/vue-echarts#79]
我註冊了兩個 theme : light / dark
是否可能根據某個 store 的布林值來動態改變 theme 呢？

查了文件好像沒有相關的方法，特來請教！

**Comment by Justineo** [comment]
ECharts 实例在初始化时就决定了 theme 了，如果有这个需求，可能需要重新初始化图表实例。目前最快的解决方法是，写两个 chart 组件实例，分别用 v-if 对应到当前的 theme。

**Comment by Justineo** [comment]
现在的版本已经会在 `theme` 变化时动态刷新了。
