### ISSUE TITLE
整个echarts过大，希望能有单独引用的方法，比如单独引用pie饼图

### ISSUE THREAD

**Issue by vopjie** [Justineo/vue-echarts#8]
thanks for you job anyway

**Comment by Justineo** [comment]
https://github.com/Justineo/vue-echarts/issues/4#issuecomment-233881455 用这种方式呢？

**Comment by vopjie** [comment]
@Justineo 怎么弄，我没懂？

**Comment by Justineo** [comment]
`dist` 下的版本是把标准版 ECharts 直接打包进去的。

想单独引用的话，就自己引入 `vue-echarts/src/components/ECharts.vue` 和 `echarts` 来打包咯。

**Comment by vopjie** [comment]
@Justineo thanks
