### ISSUE TITLE
Vue-Echarts  is not working in IE9+ , only working in chrome/firefox

### ISSUE THREAD

**Issue by Narayana84** [Justineo/vue-echarts#81]
Error in mounted hook: "TypeError: Invalid calling object"
TypeError: Invalid calling object
at Animation.prototype._startLoop (eval code:177:13)
at Animation.prototype.start (eval code:188:13)

**Comment by Justineo** [comment]
It seems to be a problem of ECharts itself.

**Comment by Justineo** [comment]
It's caused by https://github.com/ecomfe/zrender/issues/189.

Quick fix: use options without `eval` for webpack devtool configs.
