### ISSUE TITLE
Is there any solutions to combine echarts-liquidfill with vue-echarts?

### ISSUE THREAD

**Issue by DanielWLam** [Justineo/vue-echarts#82]
Sorry to borther, but is there any solutions to combine these two to use in Vue program and webpack?

**Comment by DanielWLam** [comment]
[echarts-liquidfill](https://github.com/ecomfe/echarts-liquidfill)

**Comment by Justineo** [comment]
The logo of Vue-ECharts' [demo](https://justineo.github.io/vue-echarts/demo/) is already a combination of these two projects. You can look into the demo first.
* [Demo.vue](https://github.com/Justineo/vue-echarts/blob/master/demo/Demo.vue)
* [data/logo.js](https://github.com/Justineo/vue-echarts/blob/master/demo/data/logo.js)

**Comment by DanielWLam** [comment]
Hi, I just checked the demo and my code. I don't see the problem. However it still reports this error. Here is the error and my code I captured: 
![image](https://cloud.githubusercontent.com/assets/8369212/26289624/1f4604b8-3ed4-11e7-9515-76eb8e1de108.png)

![image](https://cloud.githubusercontent.com/assets/8369212/26289653/6ad1d04c-3ed4-11e7-9a02-82fa6c52ee67.png)

**Comment by DanielWLam** [comment]
```
"echarts-liquidfill": "^1.0.5",
"vue": "^2.2.2",
"vue-echarts": "^2.3.3",
```
Besides, module's infomation in package.json is shown above.

**Comment by DanielWLam** [comment]
![image](https://cloud.githubusercontent.com/assets/8369212/26298542/472a3d06-3f0a-11e7-9957-4d5c7b3822bf.png)

@Justineo Hi, I guess I have found the solution. Just like the readme.md you metioned. echarts-liquidfill needs to be added as resolve('node_modules/echarts-liquidfill'). Otherwise, webpack2 would just ignore it. However, there is another problem shows up... 
![image](https://cloud.githubusercontent.com/assets/8369212/26298523/3687d1c0-3f0a-11e7-89c6-bec7800cd490.png)

**Comment by DanielWLam** [comment]
Hi，I just find out the reason that cause the problom above whitch is the echarts and zrender build in echart-liquidfill. However, I compare the echarts and zrender in echarts-liquidfill and those in the root node_modules. There are no difference at all. so why is that happend?

**Comment by DanielWLam** [comment]
I think I finally find out the real reason why browser would throw that error! The echarts module build in echart-liquidfill is old. Some modules like 'Model' still use `define` to declare a module

**Comment by DanielWLam** [comment]
It must have something to do with the build in node_modules

**Comment by Justineo** [comment]
Hi, is the problem still unsolved? Maybe you can update the related packages to latest versions and see if the problem still goes on.

**Comment by DanielWLam** [comment]
You mean echarts-liquid?

**Comment by DanielWLam** [comment]
Well, if i upgrade my npm to version 4, the problem would not show up anymore. I am pretty sure it has something to do with the echarts-liquidfill itself. However, I am so curioused about the reason.

**Comment by Justineo** [comment]
I mean the latest version of vue-echarts and echarts-liquidfill.

**Comment by Justineo** [comment]
Closing now, feel free to reopen if you still have this issue.
