### ISSUE TITLE
I wanna see some instance, but I cannot run this project in my machine~

### ISSUE THREAD

**Issue by TingYinHelen** [Justineo/vue-echarts#84]
I ran `cnpm install`,then error occured
![2017-05-22 12 46 03](https://cloud.githubusercontent.com/assets/14006826/26293070/8cf349c6-3eed-11e7-9f31-22b333f4538a.png)
so I modified the `package.json`,like this:
<img width="333" alt="2017-05-22 12 53 36" src="https://cloud.githubusercontent.com/assets/14006826/26293103/b7207c46-3eed-11e7-94ce-7a737b41b885.png">
But it still not works :(

**Comment by Justineo** [comment]
Hi, the latest version should solve this problem. Welcome to try and reopen this issue if the problem still exists.
