### ISSUE TITLE
引入 echarts-liquidfill 插件报错

### ISSUE THREAD

**Issue by koromon** [Justineo/vue-echarts#85]
通过 vue-cli 构建的 'webpack-simple'  模板
```
// 全局引入 Echarts
import ECharts from 'vue-echarts';
Vue.component('chart', ECharts)
```
```
// webpack.config.js 配置
{
        test: /\.js$/,
        loader: 'babel-loader',
        include: /node_modules\/echarts-liquidfill/,
        exclude: /node_modules(?![\\/]echarts-liquidfill[\\/])/
 }
```
```
// 组件页面
import 'echarts-liquidfill'

<chart :options="liquidOption"></chart>
```
![2017-05-23 5 17 31](https://cloud.githubusercontent.com/assets/13466007/26347312/bf811258-3fdb-11e7-8c61-569753a33751.png)

能否帮忙指点一下呢？谢谢

**Comment by Justineo** [comment]
不要引入预编译的版本试试呢？

像[这样](https://github.com/Justineo/vue-echarts#es-modules-with-npm--vue-loader-recommended)，引入源码版本，才能保证插件和 Vue-ECharts 作用在同一个 ECharts 包上。

不过这样需要你自行引入用到的图表和组件，优点是会减小整个项目的体积，也方便引入插件。

**Comment by koromon** [comment]
谢谢回复，最终使用了'webpack' 模板 + 源码版本，成功使用 echarts-liquidfill 插件。

**Comment by yansenlei** [comment]
我这样做还是解决不了..
version:
"vue-echarts": "^2.4.0",
"echarts-liquidfill": "^1.1.0”,

conf:
      {
        test: /\.js$/,
        loader: 'babel-loader',
        include: /node_modules\/echarts-liquidfill/,
        exclude: /node_modules(?![\\/]echarts-liquidfill[\\/])/
      },

code:
import VueECharts from 'vue-echarts/components/ECharts.vue’
import 'echarts-liquidfill/src/liquidFill.js’

**Comment by Justineo** [comment]
https://github.com/Justineo/vue-echarts/blob/a272a3bd3bbc542cdb0c4a6df09fb2c120068879/demo/Demo.vue#L267
