### ISSUE TITLE
causes error when running "npm i"

### ISSUE THREAD

**Issue by dqj** [Justineo/vue-echarts#86]
> cross-env NODE_ENV=production rollup -c

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn rollup ENOENT
    at exports._errnoException (util.js:1036:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:592:11)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

npm ERR! Darwin 16.5.0
npm ERR! argv "/Users/qj/.nvm/versions/node/v6.7.0/bin/node" "/Users/qj/.nvm/versions/node/v6.7.0/bin/npm" "run" "build"
npm ERR! node v6.7.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! vue-echarts@2.3.8 build: `cross-env NODE_ENV=production rollup -c`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vue-echarts@2.3.8 build script 'cross-env NODE_ENV=production rollup -c'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the vue-echarts package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cross-env NODE_ENV=production rollup -c
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs vue-echarts
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls vue-echarts
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/qj/Work/FE/vue-echarts/npm-debug.log

npm WARN vue-echarts@2.3.8 requires a peer of vue@^2.2.6 but none was installed.
npm WARN rollup-plugin-vue@2.4.0 requires a peer of vue@* but none was installed.
npm WARN vue-echarts@2.3.8 No repository field.
npm ERR! Darwin 16.5.0
npm ERR! argv "/Users/qj/.nvm/versions/node/v6.7.0/bin/node" "/Users/qj/.nvm/versions/node/v6.7.0/bin/npm" "i"
npm ERR! node v6.7.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! vue-echarts@2.3.8 prepublish: `npm run demo && npm run build && cp -r ./src/* . && rm index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vue-echarts@2.3.8 prepublish script 'npm run demo && npm run build && cp -r ./src/* . && rm index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the vue-echarts package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run demo && npm run build && cp -r ./src/* . && rm index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs vue-echarts
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls vue-echarts
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:

**Comment by Justineo** [comment]
Hi, the latest version should solve this problem. Welcome to try and reopen this issue if the problem still exists.
