### ISSUE TITLE
插件用不了map，我要用中国地图，每次引入都只出来南海那块

### ISSUE THREAD

**Issue by zhuzheng314** [Justineo/vue-echarts#88]
项目中引入的别的插件都可以运行，就地图出问题，是要额外引入别的吗

**Comment by Justineo** [comment]
没有错误信息、没有你的引入方式，很难提供帮助。

**Comment by zhuzheng314** [comment]
import VueECharts from 'vue-echarts'

Vue.component('chart', VueECharts)



我是这样引入的，别的饼图、柱状图、折线图都能成功显示

**Comment by zhuzheng314** [comment]
![image](https://cloud.githubusercontent.com/assets/13705072/26518379/3e028a0e-42e2-11e7-880d-164872df0f04.png)

**Comment by zhuzheng314** [comment]
地图这块就这样显示了

**Comment by zhuzheng314** [comment]
`<template>
  <chart :options="option"></chart>
</template>
<style scoped>
.echarts{
  width: 100%;
  height: 100%;
}
</style>
<script type="text/ecmascript-6">
export default {
  data: function() {
    return {
      option: {
        tooltip: {
          trigger: 'item'
        },
        grid: {
          top: '30%',
          left: '3%',
          right: '4%',
          bottom: '3%',
          containLabel: true
        },
        visualMap: {
          min: 0,
          max: 2500,
        },
        series: [
          {
            name: 'iphone3',
            type: 'map',
            mapType: 'china',
            roam: false,
            label: {
              normal: {
                show: false
              },
              emphasis: {
                show: true
              }
            },
            data: [
              { name: '北京', value: 1 },
              { name: '天津', value: 5 },
              { name: '新疆', value: 50 },
              { name: '澳门', value: 50 }
            ]
          }
        ]
      }
    }
  }
}
</script>
`

**Comment by zhuzheng314** [comment]
<template>
  <chart :options="option"></chart>
</template>
<style scoped>
.echarts{
  width: 100%;
  height: 100%;
}
</style>
<script type="text/ecmascript-6">
export default {
  data: function() {
    return {
      option: {
        tooltip: {
          trigger: 'item'
        },
        grid: {
          top: '30%',
          left: '3%',
          right: '4%',
          bottom: '3%',
          containLabel: true
        },
        visualMap: {
          min: 0,
          max: 2500,
        },
        series: [
          {
            name: 'iphone3',
            type: 'map',
            mapType: 'china',
            roam: false,
            label: {
              normal: {
                show: false
              },
              emphasis: {
                show: true
              }
            },
            data: [
              { name: '北京', value: 1 },
              { name: '天津', value: 5 },
              { name: '新疆', value: 50 },
              { name: '澳门', value: 50 }
            ]
          }
        ]
      }
    }
  }
}
</script>

**Comment by zhuzheng314** [comment]
`<template>
  <chart :options="option"></chart>
</template>
<style scoped>
.echarts{
  width: 100%;
  height: 100%;
}
</style>
<script type="text/ecmascript-6">
export default {
  data: function() {
    return {
      option: {
        tooltip: {
          trigger: 'item'
        },
        grid: {
          top: '30%',
          left: '3%',
          right: '4%',
          bottom: '3%',
          containLabel: true
        },
        visualMap: {
          min: 0,
          max: 2500,
        },
        series: [
          {
            name: 'iphone3',
            type: 'map',
            mapType: 'china',
            roam: false,
            label: {
              normal: {
                show: false
              },
              emphasis: {
                show: true
              }
            },
            data: [
              { name: '北京', value: 1 },
              { name: '天津', value: 5 },
              { name: '新疆', value: 50 },
              { name: '澳门', value: 50 }
            ]
          }
        ]
      }
    }
  }
}
</script>
`

**Comment by zhuzheng314** [comment]
`export default {
  data: function() {
    return {
      option: {
        tooltip: {
          trigger: 'item'
        },
        grid: {
          top: '3%',
          left: '3%',
          right: '4%',
          bottom: '3%',
          containLabel: true
        },
        visualMap: {
          min: 0,
          max: 2500,
        },
        series: [
          {
            name: 'iphone3',
            type: 'map',
            mapType: 'china',
            roam: false,
            label: {
              normal: {
                show: false
              },
              emphasis: {
                show: true
              }
            },
            data: [
              { name: '北京', value: 1 },
              { name: '天津', value: 5 },
              { name: '新疆', value: 50 },
              { name: '澳门', value: 50 }
            ]
          }
        ]
      }
    }
  }
}`

**Comment by zhuzheng314** [comment]
```javascript
function fancyAlert(arg) {
  if(arg) {
    $.facebox({div:'#foo'})
  }
}
```

**Comment by zhuzheng314** [comment]
```javascript
export default {
  data: function() {
    return {
      option: {
        tooltip: {
          trigger: 'item'
        },
        grid: {
          top: '30%',
          left: '3%',
          right: '4%',
          bottom: '3%',
          containLabel: true
        },
        visualMap: {
          min: 0,
          max: 2500,
        },
        series: [
          {
            name: 'iphone3',
            type: 'map',
            mapType: 'china',
            roam: false,
            label: {
              normal: {
                show: false
              },
              emphasis: {
                show: true
              }
            },
            data: [
              { name: '北京', value: 1 },
              { name: '天津', value: 5 },
              { name: '新疆', value: 50 },
              { name: '澳门', value: 50 }
            ]
          }
        ]
      }
    }
  }
}
```

**Comment by zhuzheng314** [comment]
![image](https://cloud.githubusercontent.com/assets/13705072/26518437/36c7ab56-42e3-11e7-8673-de247acb82da.png)

**Comment by Justineo** [comment]
看 [demo](https://github.com/Justineo/vue-echarts/blob/9a6d937dd2179d23dc746be8fce59898ace2170e/demo/Demo.vue#L280) 里写的，需要引入地图数据。你看看 ECharts 的文档也能知道。
