### ISSUE TITLE
使用webpack的externals来指定echarts无法减少包的大小

### ISSUE THREAD

**Issue by SidKwok** [Justineo/vue-echarts#92]
重现步骤：
1. 在vue-cli/webpack的`webpack.base.conf.js`中加入:
```javascript
externals: {
  'echarts': 'window.echarts'
}
```
2. 打包出来的vendor大小是 713kb

3. 去掉externals打包出来的vendor大小是：713kb

还是把所有东西打包到bundle中去了，有解决方法吗？还是说我的使用方式有问题？

我是想通过script方式引入echarts来并行加载echarts的

**Comment by Justineo** [comment]
`vue-echarts` 没有引入 `echarts`，引入的是 `echarts/lib/echarts`。我感觉是和这个有关。

**Comment by blusewang** [comment]
我也是，全写成`require('echarts')`也没用！
@SidKwok 楼主有解决么？
这货太TM大了！

**Comment by Justineo** [comment]
我理解不应该把 `echarts` 单独放到一个 `<script>` 加载然后通过全局变量引用呀，是否尝试过使用 webpack 自带的 [code split](https://webpack.js.org/guides/code-splitting/) 功能呢？

**Comment by Justineo** [comment]
如果 code split 无效，再讨论这个 issue。先关闭了。

**Comment by Xixi20160512** [comment]
@Justineo 尝试过 使用commonsChunk无法剥离出echarts

**Comment by vkboo** [comment]
参考[webpack官方文档](https://webpack.docschina.org/guides/author-libraries/#%E5%A4%96%E9%83%A8%E5%8C%96-lodash),实际测试可用。
![image](https://user-images.githubusercontent.com/17156560/86897383-eb1c0480-c139-11ea-83bf-dbdcd739d86c.png)

**Comment by wunai006** [comment]
不要用require，直接在main.js中import 然后vue.use就行。
1. 在webpack.base.config.js中加入externals的echarts
2. 在最外层的index.js加入cdn引入(就是<script src=""></script>)
3. 在main.js照常引入echarts
我这样打包下来就只有几k

**Comment by lizehua-cn** [comment]
> 参考[webpack官方文档](https://webpack.docschina.org/guides/author-libraries/#%E5%A4%96%E9%83%A8%E5%8C%96-lodash),实际测试可用。
> ![image](https://user-images.githubusercontent.com/17156560/86897383-eb1c0480-c139-11ea-83bf-dbdcd739d86c.png)

还是了解太少了, `externals`用数组的形式就报错, 改成默认对象就可以了
```
    externals: {
      jquery: 'jQuery',
      echarts: /echarts\/.+$/
    }
```

**Comment by EMMMMMMMMMMMMM** [comment]
> 参考[webpack官方文档](https://webpack.docschina.org/guides/author-libraries/#%E5%A4%96%E9%83%A8%E5%8C%96-lodash),实际测试可用。
> ![image](https://user-images.githubusercontent.com/17156560/86897383-eb1c0480-c139-11ea-83bf-dbdcd739d86c.png)

确实解决了问题, 棒棒!
