### ISSUE TITLE
Error in mounted hook

### ISSUE THREAD

**Issue by acodercat** [Justineo/vue-echarts#95]
[Vue warn]: Error in mounted hook: "Error: Component series.line not exists. Load it first."

found in

---> <Chart> at C:\Users\Cat\Desktop\vue\jinsui\node_modules\vue-echarts\components\ECharts.vue
       <Top> at C:\Users\Cat\Desktop\vue\jinsui\src\components\top.vue
         <Dashboard> at C:\Users\Cat\Desktop\vue\jinsui\src\views\dashboard\dashboard.vue
           <App> at C:\Users\Cat\Desktop\vue\jinsui\src\App.vue
             <Root>

**Comment by Justineo** [comment]
Please follow the instructions in the [README](https://github.com/Justineo/vue-echarts#es-modules-with-npm--vue-loader-recommended) and [the docs of ECharts](http://echarts.baidu.com/tutorial.html#%E5%9C%A8%20webpack%20%E4%B8%AD%E4%BD%BF%E7%94%A8%20ECharts). You have to manually import ECharts components you are using like this:

```js
import 'echarts/lib/chart/bar'
import 'echarts/lib/component/tooltip'
```

**Comment by acodercat** [comment]
还是这样vue.esm.js?65d7:523 Error: Component series.line not exists. Load it first.

**Comment by Justineo** [comment]
请完整读完文档，确保你已经引入了必须的模块。我给你贴的只是示例。
