### ISSUE TITLE
不兼容ie和edge

### ISSUE THREAD

**Issue by JhonMr** [Justineo/vue-echarts#96]
在ie和edge会报错
[Vue warn]: Error in mounted hook: 
(found in <Chart> at D:\projects\vuenoEslint\node_modules\vue-echarts\components\ECharts.vue)
[object Error]{description: "调用的对象无效", message: "调用的对象无效", name: "TypeError", number: -2147418113, stack: "TypeError: ..."}
![image](https://user-images.githubusercontent.com/12690459/27462971-0b81743a-57f7-11e7-9476-71d4ad313226.png)

**Comment by Justineo** [comment]
不是本项目的问题，见 #81。
