### ISSUE TITLE
怎么得到init后的实例

### ISSUE THREAD

**Issue by acodercat** [Justineo/vue-echarts#98]
我需要使用setOption

**Comment by Justineo** [comment]
发 issue 前先看一下 README 吧。

**Comment by acodercat** [comment]
没看懂，看了demo里面也没有

**Comment by Justineo** [comment]
![image](https://user-images.githubusercontent.com/1726061/27530215-3f5c7508-5a8a-11e7-815f-ad76104fd34d.png)
