### ISSUE TITLE
用了字符云echarts-wordcloud，切换到其他有echarts的页面报错

### ISSUE THREAD

**Issue by hank2718** [Justineo/vue-echarts#99]
![image](https://user-images.githubusercontent.com/7368299/27580139-54ea494a-5b5c-11e7-81ca-2a428864fee2.png)
![image](https://user-images.githubusercontent.com/7368299/27580157-66eb6552-5b5c-11e7-8c7f-cdd3902c00a1.png)

**Comment by pissang** [comment]
问题描述具体点？

**Comment by Justineo** [comment]
什么叫切换页面？你的描述太简单，光看报错信息无法找到问题。

**Comment by hank2718** [comment]
如果我在a页面，a页面是用了echarts-wordcloud，a页面没问题，这时候切换b页面，b页面有饼图线图等等，这时候页面就报错了

**Comment by Justineo** [comment]
a 页面，b 页面，还是没有描述是怎么切换的……vue-router？

**Comment by hank2718** [comment]
router切换   不缓存路由组件

**Comment by Justineo** [comment]
See #101.
